# NORTHWIND DATABASE

El **objetivo** de este ejercicio es generar una serie de consultas SQL que permitan extraer información relevante de la base de datos y luego exportar los resultados para construir dashboards o visualizaciones que proporcionen insights valiosos para la toma de decisiones empresariales.

La base de datos Northwind es una base de datos de ejemplo clásica que simula las operaciones de una empresa minorista. Contiene tablas relacionales que representan diferentes aspectos del negocio, como productos, clientes, pedidos y empleados. Utilizando consultas SQL, podrás explorar y analizar estos datos para comprender mejor el desempeño del negocio en diferentes áreas.

Una vez que hayas realizado las consultas SQL y obtenido los resultados, podrás utilizarlos para herramientas de visualización de datos como Tableau, Power BI, Streamlit o cualquier otra herramienta de tu elección.

![img](./img/northwind-er-diagram.png)

Tendrás que elegir uno de los retos a resolver:

In [391]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import sqlite3
# plotly
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)

# word cloud library
import wordcloud
import plotly.graph_objs as go
# matplotlib
import matplotlib.pyplot as plt

### **1. Análisis de Ventas por Región**
Analiza las ventas de productos por región. El objetivo es identificar las regiones que generan más ingresos y las tendencias de ventas a lo largo del tiempo en esas regiones. 
Pista: Utiliza gráficos de barras y líneas para mostrar la evolución de las ventas, así como mapas geográficos para visualizar la distribución de ingresos por región.

In [392]:

# Connect to the DB
conn = sqlite3.connect("data/northwind.db")
c = conn.cursor();

In [393]:
c.execute("""SELECT name FROM sqlite_master WHERE type='table';""").fetchall()

[('Categories',),
 ('sqlite_sequence',),
 ('CustomerCustomerDemo',),
 ('CustomerDemographics',),
 ('Customers',),
 ('Employees',),
 ('EmployeeTerritories',),
 ('Order Details',),
 ('Orders',),
 ('Products',),
 ('Regions',),
 ('Shippers',),
 ('Suppliers',),
 ('Territories',)]

In [394]:
c.execute("""
          SELECT*
          from products AS p
          INNER JOIN suppliers AS s ON s.supplierid=p.supplierid

"""
).fetchall()

[(1,
  'Chai',
  1,
  1,
  '10 boxes x 20 bags',
  18,
  39,
  0,
  10,
  '0',
  1,
  'Exotic Liquids',
  'Charlotte Cooper',
  'Purchasing Manager',
  '49 Gilbert St.',
  'London',
  'British Isles',
  'EC1 4SD',
  'UK',
  '(171) 555-2222',
  None,
  None),
 (2,
  'Chang',
  1,
  1,
  '24 - 12 oz bottles',
  19,
  17,
  40,
  25,
  '0',
  1,
  'Exotic Liquids',
  'Charlotte Cooper',
  'Purchasing Manager',
  '49 Gilbert St.',
  'London',
  'British Isles',
  'EC1 4SD',
  'UK',
  '(171) 555-2222',
  None,
  None),
 (3,
  'Aniseed Syrup',
  1,
  2,
  '12 - 550 ml bottles',
  10,
  13,
  70,
  25,
  '0',
  1,
  'Exotic Liquids',
  'Charlotte Cooper',
  'Purchasing Manager',
  '49 Gilbert St.',
  'London',
  'British Isles',
  'EC1 4SD',
  'UK',
  '(171) 555-2222',
  None,
  None),
 (4,
  "Chef Anton's Cajun Seasoning",
  2,
  2,
  '48 - 6 oz jars',
  22,
  53,
  0,
  0,
  '0',
  2,
  'New Orleans Cajun Delights',
  'Shelley Burke',
  'Order Administrator',
  'P.O. Box 78934',
  'New Orleans',
  'North America',
  '70117',
  'USA',
  '(100) 555-4822',
  None,
  '#CAJUN.HTM#'),
 (5,
  "Chef Anton's Gumbo Mix",
  2,
  2,
  '36 boxes',
  21.35,
  0,
  0,
  0,
  '1',
  2,
  'New Orleans Cajun Delights',
  'Shelley Burke',
  'Order Administrator',
  'P.O. Box 78934',
  'New Orleans',
  'North America',
  '70117',
  'USA',
  '(100) 555-4822',
  None,
  '#CAJUN.HTM#'),
 (6,
  "Grandma's Boysenberry Spread",
  3,
  2,
  '12 - 8 oz jars',
  25,
  120,
  0,
  25,
  '0',
  3,
  "Grandma Kelly's Homestead",
  'Regina Murphy',
  'Sales Representative',
  '707 Oxford Rd.',
  'Ann Arbor',
  'North America',
  '48104',
  'USA',
  '(313) 555-5735',
  '(313) 555-3349',
  None),
 (7,
  "Uncle Bob's Organic Dried Pears",
  3,
  7,
  '12 - 1 lb pkgs.',
  30,
  15,
  0,
  10,
  '0',
  3,
  "Grandma Kelly's Homestead",
  'Regina Murphy',
  'Sales Representative',
  '707 Oxford Rd.',
  'Ann Arbor',
  'North America',
  '48104',
  'USA',
  '(313) 555-5735',
  '(313) 555-3349',
  None),
 (8,
  'Northwoods Cranberry Sauce',
  3,
  2,
  '12 - 12 oz jars',
  40,
  6,
  0,
  0,
  '0',
  3,
  "Grandma Kelly's Homestead",
  'Regina Murphy',
  'Sales Representative',
  '707 Oxford Rd.',
  'Ann Arbor',
  'North America',
  '48104',
  'USA',
  '(313) 555-5735',
  '(313) 555-3349',
  None),
 (9,
  'Mishi Kobe Niku',
  4,
  6,
  '18 - 500 g pkgs.',
  97,
  29,
  0,
  0,
  '1',
  4,
  'Tokyo Traders',
  'Yoshi Nagase',
  'Marketing Manager',
  '9-8 Sekimai\nMusashino-shi',
  'Tokyo',
  'Eastern Asia',
  '100',
  'Japan',
  '(03) 3555-5011',
  None,
  None),
 (10,
  'Ikura',
  4,
  8,
  '12 - 200 ml jars',
  31,
  31,
  0,
  0,
  '0',
  4,
  'Tokyo Traders',
  'Yoshi Nagase',
  'Marketing Manager',
  '9-8 Sekimai\nMusashino-shi',
  'Tokyo',
  'Eastern Asia',
  '100',
  'Japan',
  '(03) 3555-5011',
  None,
  None),
 (11,
  'Queso Cabrales',
  5,
  4,
  '1 kg pkg.',
  21,
  22,
  30,
  30,
  '0',
  5,
  "Cooperativa de Quesos 'Las Cabras'",
  'Antonio del Valle Saavedra ',
  'Export Administrator',
  'Calle del Rosal 4',
  'Oviedo',
  'Southern Europe',
  '33007',
  'Spain',
  '(98) 598 76 54',
  None,
  None),
 (12,
  'Queso Manchego La Pastora',
  5,
  4,
  '10 - 500 g pkgs.',
  38,
  86,
  0,
  0,
  '0',
  5,
  "Cooperativa de Quesos 'Las Cabras'",
  'Antonio del Valle Saavedra ',
  'Export Administrator',
  'Calle del Rosal 4',
  'Oviedo',
  'Southern Europe',
  '33007',
  'Spain',
  '(98) 598 76 54',
  None,
  None),
 (13,
  'Konbu',
  6,
  8,
  '2 kg box',
  6,
  24,
  0,
  5,
  '0',
  6,
  "Mayumi's",
  'Mayumi Ohno',
  'Marketing Representative',
  '92 Setsuko\nChuo-ku',
  'Osaka',
  'Eastern Asia',
  '545',
  'Japan',
  '(06) 431-7877',
  None,
  "Mayumi's (on the World Wide Web)#http://www.microsoft.com/accessdev/sampleapps/mayumi.htm#"),
 (14,
  'Tofu',
  6,
  7,
  '40 - 100 g pkgs.',
  23.25,
  35,
  0,
  0,
  '0',
  6,
  "Mayumi's",
  'Mayumi Ohno',
  'Marketing Representative',
  '92 Setsuko\nChuo-ku',
  'Osaka',
  'Eastern Asia',
  '545',
  'Japan',
  '(06) 431-7877',
  None,
  "Mayumi's (on the World Wide Web)#http://www.microsoft.com/accessdev/sampleapps/mayumi.htm#"),
 (15,
  'Genen Shouyu',
  6,
  2,
  '24 - 250 ml bottles',
  15.5,
  39,
  0,
  5,
  '0',
  6,
  "Mayumi's",
  'Mayumi Ohno',
  'Marketing Representative',
  '92 Setsuko\nChuo-ku',
  'Osaka',
  'Eastern Asia',
  '545',
  'Japan',
  '(06) 431-7877',
  None,
  "Mayumi's (on the World Wide Web)#http://www.microsoft.com/accessdev/sampleapps/mayumi.htm#"),
 (16,
  'Pavlova',
  7,
  3,
  '32 - 500 g boxes',
  17.45,
  29,
  0,
  10,
  '0',
  7,
  'Pavlova, Ltd.',
  'Ian Devling',
  'Marketing Manager',
  '74 Rose St.\nMoonie Ponds',
  'Melbourne',
  'Victoria',
  '3058',
  'Australia',
  '(03) 444-2343',
  '(03) 444-6588',
  None),
 (17,
  'Alice Mutton',
  7,
  6,
  '20 - 1 kg tins',
  39,
  0,
  0,
  0,
  '1',
  7,
  'Pavlova, Ltd.',
  'Ian Devling',
  'Marketing Manager',
  '74 Rose St.\nMoonie Ponds',
  'Melbourne',
  'Victoria',
  '3058',
  'Australia',
  '(03) 444-2343',
  '(03) 444-6588',
  None),
 (18,
  'Carnarvon Tigers',
  7,
  8,
  '16 kg pkg.',
  62.5,
  42,
  0,
  0,
  '0',
  7,
  'Pavlova, Ltd.',
  'Ian Devling',
  'Marketing Manager',
  '74 Rose St.\nMoonie Ponds',
  'Melbourne',
  'Victoria',
  '3058',
  'Australia',
  '(03) 444-2343',
  '(03) 444-6588',
  None),
 (19,
  'Teatime Chocolate Biscuits',
  8,
  3,
  '10 boxes x 12 pieces',
  9.2,
  25,
  0,
  5,
  '0',
  8,
  'Specialty Biscuits, Ltd.',
  'Peter Wilson',
  'Sales Representative',
  "29 King's Way",
  'Manchester',
  'British Isles',
  'M14 GSD',
  'UK',
  '(161) 555-4448',
  None,
  None),
 (20,
  "Sir Rodney's Marmalade",
  8,
  3,
  '30 gift boxes',
  81,
  40,
  0,
  0,
  '0',
  8,
  'Specialty Biscuits, Ltd.',
  'Peter Wilson',
  'Sales Representative',
  "29 King's Way",
  'Manchester',
  'British Isles',
  'M14 GSD',
  'UK',
  '(161) 555-4448',
  None,
  None),
 (21,
  "Sir Rodney's Scones",
  8,
  3,
  '24 pkgs. x 4 pieces',
  10,
  3,
  40,
  5,
  '0',
  8,
  'Specialty Biscuits, Ltd.',
  'Peter Wilson',
  'Sales Representative',
  "29 King's Way",
  'Manchester',
  'British Isles',
  'M14 GSD',
  'UK',
  '(161) 555-4448',
  None,
  None),
 (22,
  "Gustaf's Knäckebröd",
  9,
  5,
  '24 - 500 g pkgs.',
  21,
  104,
  0,
  25,
  '0',
  9,
  'PB Knäckebröd AB',
  'Lars Peterson',
  'Sales Agent',
  'Kaloadagatan 13',
  'Göteborg',
  None,
  'S-345 67',
  'Sweden ',
  '031-987 65 43',
  '031-987 65 91',
  None),
 (23,
  'Tunnbröd',
  9,
  5,
  '12 - 250 g pkgs.',
  9,
  61,
  0,
  25,
  '0',
  9,
  'PB Knäckebröd AB',
  'Lars Peterson',
  'Sales Agent',
  'Kaloadagatan 13',
  'Göteborg',
  None,
  'S-345 67',
  'Sweden ',
  '031-987 65 43',
  '031-987 65 91',
  None),
 (24,
  'Guaraná Fantástica',
  10,
  1,
  '12 - 355 ml cans',
  4.5,
  20,
  0,
  0,
  '1',
  10,
  'Refrescos Americanas LTDA',
  'Carlos Diaz',
  'Marketing Manager',
  'Av. das Americanas 12.890',
  'São Paulo',
  'South America',
  '5442',
  'Brazil',
  '(11) 555 4640',
  None,
  None),
 (25,
  'NuNuCa Nuß-Nougat-Creme',
  11,
  3,
  '20 - 450 g glasses',
  14,
  76,
  0,
  30,
  '0',
  11,
  'Heli Süßwaren GmbH & Co. KG',
  'Petra Winkler',
  'Sales Manager',
  'Tiergartenstraße 5',
  'Berlin',
  'Western Europe',
  '10785',
  'Germany',
  '(010) 9984510',
  None,
  None),
 (26,
  'Gumbär Gummibärchen',
  11,
  3,
  '100 - 250 g bags',
  31.23,
  15,
  0,
  0,
  '0',
  11,
  'Heli Süßwaren GmbH & Co. KG',
  'Petra Winkler',
  'Sales Manager',
  'Tiergartenstraße 5',
  'Berlin',
  'Western Europe',
  '10785',
  'Germany',
  '(010) 9984510',
  None,
  None),
 (27,
  'Schoggi Schokolade',
  11,
  3,
  '100 - 100 g pieces',
  43.9,
  49,
  0,
  30,
  '0',
  11,
  'Heli Süßwaren GmbH & Co. KG',
  'Petra Winkler',
  'Sales Manager',
  'Tiergartenstraße 5',
  'Berlin',
  'Western Europe',
  '10785',
  'Germany',
  '(010) 9984510',
  None,
  None),
 (28,
  'Rössle Sauerkraut',
  12,
  7,
  '25 - 825 g cans',
  45.6,
  26,
  0,
  0,
  '1',
  12,
  'Plutzer Lebensmittelgroßmärkte AG',
  'Martin Bein',
  'International Marketing Mgr.',
  'Bogenallee 51',
  'Frankfurt',
  'Western Europe',
  '60439',
  'Germany',
  '(069) 992755',
  None,
  'Plutzer (on the World Wide Web)#http://www.microsoft.com/accessdev/sampleapps/plutzer.htm#'),
 (29,
  'Thüringer Rostbratwurst',
  12,
  6,
  '50 bags x 30 sausgs.',
  123.79,
  0,
  0,
  0,
  '1',
  12,
  'Plutzer Lebensmittelgroßmärkte AG',
  'Martin Bein',
  'International Marketing Mgr.',
  'Bogenallee 51',
  'Frankfurt',
  'Western Europe',
  '60439',
  'Germany',
  '(069) 992755',
  None,
  'Plutzer (on the World Wide Web)#http://www.microsoft.com/accessdev/sampleapps/plutzer.htm#'),
 (30,
  'Nord-Ost Matjeshering',
  13,
  8,
  '10 - 200 g glasses',
  25.89,
  10,
  0,
  15,
  '0',
  13,
  'Nord-Ost-Fisch Handelsgesellschaft mbH',
  'Sven Petersen',
  'Coordinator Foreign Markets',
  'Frahmredder 112a',
  'Cuxhaven',
  'Western Europe',
  '27478',
  'Germany',
  '(04721) 8713',
  '(04721) 8714',
  None),
 (31,
  'Gorgonzola Telino',
  14,
  4,
  '12 - 100 g pkgs',
  12.5,
  0,
  70,
  20,
  '0',
  14,
  'Formaggi Fortini s.r.l.',
  'Elio Rossi',
  'Sales Representative',
  'Viale Dante, 75',
  'Ravenna',
  'Southern Europe',
  '48100',
  'Italy',
  '(0544) 60323',
  '(0544) 60603',
  '#FORMAGGI.HTM#'),
 (32,
  'Mascarpone Fabioli',
  14,
  4,
  '24 - 200 g pkgs.',
  32,
  9,
  40,
  25,
  '0',
  14,
  'Formaggi Fortini s.r.l.',
  'Elio Rossi',
  'Sales Representative',
  'Viale Dante, 75',
  'Ravenna',
  'Southern Europe',
  '48100',
  'Italy',
  '(0544) 60323',
  '(0544) 60603',
  '#FORMAGGI.HTM#'),
 (33,
  'Geitost',
  15,
  4,
  '500 g',
  2.5,
  112,
  0,
  20,
  '0',
  15,
  'Norske Meierier',
  'Beate Vileid',
  'Marketing Manager',
  'Hatlevegen 5',
  'Sandvika',
  'Scandinavia',
  '1320',
  'Norway',
  '(0)2-953010',
  None,
  None),
 (34,
  'Sasquatch Ale',
  16,
  1,
  '24 - 12 oz bottles',
  14,
  111,
  0,
  15,
  '0',
  16,
  'Bigfoot Breweries',
  'Cheryl Saylor',
  'Regional Account Rep.',
  '3400 - 8th Avenue\nSuite 210',
  'Bend',
  'North America',
  '97101',
  'USA',
  '(503) 555-9931',
  None,
  None),
 (35,
  'Steeleye Stout',
  16,
  1,
  '24 - 12 oz bottles',
  18,
  20,
  0,
  15,
  '0',
  16,
  'Bigfoot Breweries',
  'Cheryl Saylor',
  'Regional Account Rep.',
  '3400 - 8th Avenue\nSuite 210',
  'Bend',
  'North America',
  '97101',
  'USA',
  '(503) 555-9931',
  None,
  None),
 (36,
  'Inlagd Sill',
  17,
  8,
  '24 - 250 g  jars',
  19,
  112,
  0,
  20,
  '0',
  17,
  'Svensk Sjöföda AB',
  'Michael Björn',
  'Sales Representative',
  'Brovallavägen 231',
  'Stockholm',
  'Northern Europe',
  'S-123 45',
  'Sweden',
  '08-123 45 67',
  None,
  None),
 (37,
  'Gravad lax',
  17,
  8,
  '12 - 500 g pkgs.',
  26,
  11,
  50,
  25,
  '0',
  17,
  'Svensk Sjöföda AB',
  'Michael Björn',
  'Sales Representative',
  'Brovallavägen 231',
  'Stockholm',
  'Northern Europe',
  'S-123 45',
  'Sweden',
  '08-123 45 67',
  None,
  None),
 (38,
  'Côte de Blaye',
  18,
  1,
  '12 - 75 cl bottles',
  263.5,
  17,
  0,
  15,
  '0',
  18,
  'Aux joyeux ecclésiastiques',
  'Guylène Nodier',
  'Sales Manager',
  '203, Rue des Francs-Bourgeois',
  'Paris',
  'Western Europe',
  '75004',
  'France',
  '(1) 03.83.00.68',
  '(1) 03.83.00.62',
  None),
 (39,
  'Chartreuse verte',
  18,
  1,
  '750 cc per bottle',
  18,
  69,
  0,
  5,
  '0',
  18,
  'Aux joyeux ecclésiastiques',
  'Guylène Nodier',
  'Sales Manager',
  '203, Rue des Francs-Bourgeois',
  'Paris',
  'Western Europe',
  '75004',
  'France',
  '(1) 03.83.00.68',
  '(1) 03.83.00.62',
  None),
 (40,
  'Boston Crab Meat',
  19,
  8,
  '24 - 4 oz tins',
  18.4,
  123,
  0,
  30,
  '0',
  19,
  'New England Seafood Cannery',
  'Robb Merchant',
  'Wholesale Account Agent',
  'Order Processing Dept.\n2100 Paul Revere Blvd.',
  'Boston',
  'North America',
  '02134',
  'USA',
  '(617) 555-3267',
  '(617) 555-3389',
  None),
 (41,
  "Jack's New England Clam Chowder",
  19,
  8,
  '12 - 12 oz cans',
  9.65,
  85,
  0,
  10,
  '0',
  19,
  'New England Seafood Cannery',
  'Robb Merchant',
  'Wholesale Account Agent',
  'Order Processing Dept.\n2100 Paul Revere Blvd.',
  'Boston',
  'North America',
  '02134',
  'USA',
  '(617) 555-3267',
  '(617) 555-3389',
  None),
 (42,
  'Singaporean Hokkien Fried Mee',
  20,
  5,
  '32 - 1 kg pkgs.',
  14,
  26,
  0,
  0,
  '1',
  20,
  'Leka Trading',
  'Chandra Leka',
  'Owner',
  '471 Serangoon Loop, Suite #402',
  'Singapore',
  'South-East Asia',
  '0512',
  'Singapore',
  '555-8787',
  None,
  None),
 (43,
  'Ipoh Coffee',
  20,
  1,
  '16 - 500 g tins',
  46,
  17,
  10,
  25,
  '0',
  20,
  'Leka Trading',
  'Chandra Leka',
  'Owner',
  '471 Serangoon Loop, Suite #402',
  'Singapore',
  'South-East Asia',
  '0512',
  'Singapore',
  '555-8787',
  None,
  None),
 (44,
  'Gula Malacca',
  20,
  2,
  '20 - 2 kg bags',
  19.45,
  27,
  0,
  15,
  '0',
  20,
  'Leka Trading',
  'Chandra Leka',
  'Owner',
  '471 Serangoon Loop, Suite #402',
  'Singapore',
  'South-East Asia',
  '0512',
  'Singapore',
  '555-8787',
  None,
  None),
 (45,
  'Rogede sild',
  21,
  8,
  '1k pkg.',
  9.5,
  5,
  70,
  15,
  '0',
  21,
  'Lyngbysild',
  'Niels Petersen',
  'Sales Manager',
  'Lyngbysild\nFiskebakken 10',
  'Lyngby',
  'Northern Europe',
  '2800',
  'Denmark',
  '43844108',
  '43844115',
  None),
 (46,
  'Spegesild',
  21,
  8,
  '4 - 450 g glasses',
  12,
  95,
  0,
  0,
  '0',
  21,
  'Lyngbysild',
  'Niels Petersen',
  'Sales Manager',
  'Lyngbysild\nFiskebakken 10',
  'Lyngby',
  'Northern Europe',
  '2800',
  'Denmark',
  '43844108',
  '43844115',
  None),
 (47,
  'Zaanse koeken',
  22,
  3,
  '10 - 4 oz boxes',
  9.5,
  36,
  0,
  0,
  '0',
  22,
  'Zaanse Snoepfabriek',
  'Dirk Luchte',
  'Accounting Manager',
  'Verkoop\nRijnweg 22',
  'Zaandam',
  'Northern Europe',
  '9999 ZZ',
  'Netherlands',
  '(12345) 1212',
  '(12345) 1210',
  None),
 (48,
  'Chocolade',
  22,
  3,
  '10 pkgs.',
  12.75,
  15,
  70,
  25,
  '0',
  22,
  'Zaanse Snoepfabriek',
  'Dirk Luchte',
  'Accounting Manager',
  'Verkoop\nRijnweg 22',
  'Zaandam',
  'Northern Europe',
  '9999 ZZ',
  'Netherlands',
  '(12345) 1212',
  '(12345) 1210',
  None),
 (49,
  'Maxilaku',
  23,
  3,
  '24 - 50 g pkgs.',
  20,
  10,
  60,
  15,
  '0',
  23,
  'Karkki Oy',
  'Anne Heikkonen',
  'Product Manager',
  'Valtakatu 12',
  'Lappeenranta',
  'Scandinavia',
  '53120',
  'Finland',
  '(953) 10956',
  None,
  None),
 (50,
  'Valkoinen suklaa',
  23,
  3,
  '12 - 100 g bars',
  16.25,
  65,
  0,
  30,
  '0',
  23,
  'Karkki Oy',
  'Anne Heikkonen',
  'Product Manager',
  'Valtakatu 12',
  'Lappeenranta',
  'Scandinavia',
  '53120',
  'Finland',
  '(953) 10956',
  None,
  None),
 (51,
  'Manjimup Dried Apples',
  24,
  7,
  '50 - 300 g pkgs.',
  53,
  20,
  0,
  10,
  '0',
  24,
  "G'day, Mate",
  'Wendy Mackenzie',
  'Sales Representative',
  "170 Prince Edward Parade\nHunter's Hill",
  'Sydney',
  'NSW',
  '2042',
  'Australia',
  '(02) 555-5914',
  '(02) 555-4873',
  "G'day Mate (on the World Wide Web)#http://www.microsoft.com/accessdev/sampleapps/gdaymate.htm#"),
 (52,
  'Filo Mix',
  24,
  5,
  '16 - 2 kg boxes',
  7,
  38,
  0,
  25,
  '0',
  24,
  "G'day, Mate",
  'Wendy Mackenzie',
  'Sales Representative',
  "170 Prince Edward Parade\nHunter's Hill",
  'Sydney',
  'NSW',
  '2042',
  'Australia',
  '(02) 555-5914',
  '(02) 555-4873',
  "G'day Mate (on the World Wide Web)#http://www.microsoft.com/accessdev/sampleapps/gdaymate.htm#"),
 (53,
  'Perth Pasties',
  24,
  6,
  '48 pieces',
  32.8,
  0,
  0,
  0,
  '1',
  24,
  "G'day, Mate",
  'Wendy Mackenzie',
  'Sales Representative',
  "170 Prince Edward Parade\nHunter's Hill",
  'Sydney',
  'NSW',
  '2042',
  'Australia',
  '(02) 555-5914',
  '(02) 555-4873',
  "G'day Mate (on the World Wide Web)#http://www.microsoft.com/accessdev/sampleapps/gdaymate.htm#"),
 (54,
  'Tourtière',
  25,
  6,
  '16 pies',
  7.45,
  21,
  0,
  10,
  '0',
  25,
  'Ma Maison',
  'Jean-Guy Lauzon',
  'Marketing Manager',
  '2960 Rue St. Laurent',
  'Montréal',
  'North America',
  'H1J 1C3',
  'Canada',
  '(514) 555-9022',
  None,
  None),
 (55,
  'Pâté chinois',
  25,
  6,
  '24 boxes x 2 pies',
  24,
  115,
  0,
  20,
  '0',
  25,
  'Ma Maison',
  'Jean-Guy Lauzon',
  'Marketing Manager',
  '2960 Rue St. Laurent',
  'Montréal',
  'North America',
  'H1J 1C3',
  'Canada',
  '(514) 555-9022',
  None,
  None),
 (56,
  'Gnocchi di nonna Alice',
  26,
  5,
  '24 - 250 g pkgs.',
  38,
  21,
  10,
  30,
  '0',
  26,
  'Pasta Buttini s.r.l.',
  'Giovanni Giudici',
  'Order Administrator',
  'Via dei Gelsomini, 153',
  'Salerno',
  'Southern Europe',
  '84100',
  'Italy',
  '(089) 6547665',
  '(089) 6547667',
  None),
 (57,
  'Ravioli Angelo',
  26,
  5,
  '24 - 250 g pkgs.',
  19.5,
  36,
  0,
  20,
  '0',
  26,
  'Pasta Buttini s.r.l.',
  'Giovanni Giudici',
  'Order Administrator',
  'Via dei Gelsomini, 153',
  'Salerno',
  'Southern Europe',
  '84100',
  'Italy',
  '(089) 6547665',
  '(089) 6547667',
  None),
 (58,
  'Escargots de Bourgogne',
  27,
  8,
  '24 pieces',
  13.25,
  62,
  0,
  20,
  '0',
  27,
  'Escargots Nouveaux',
  'Marie Delamare',
  'Sales Manager',
  '22, rue H. Voiron',
  'Montceau',
  'Western Europe',
  '71300',
  'France',
  '85.57.00.07',
  None,
  None),
 (59,
  'Raclette Courdavault',
  28,
  4,
  '5 kg pkg.',
  55,
  79,
  0,
  0,
  '0',
  28,
  'Gai pâturage',
  'Eliane Noz',
  'Sales Representative',
  'Bat. B\n3, rue des Alpes',
  'Annecy',
  'Western Europe',
  '74000',
  'France',
  '38.76.98.06',
  '38.76.98.58',
  None),
 (60,
  'Camembert Pierrot',
  28,
  4,
  '15 - 300 g rounds',
  34,
  19,
  0,
  0,
  '0',
  28,
  'Gai pâturage',
  'Eliane Noz',
  'Sales Representative',
  'Bat. B\n3, rue des Alpes',
  'Annecy',
  'Western Europe',
  '74000',
  'France',
  '38.76.98.06',
  '38.76.98.58',
  None),
 (61,
  "Sirop d'érable",
  29,
  2,
  '24 - 500 ml bottles',
  28.5,
  113,
  0,
  25,
  '0',
  29,
  "Forêts d'érables",
  'Chantal Goulet',
  'Accounting Manager',
  '148 rue Chasseur',
  'Ste-Hyacinthe',
  'North America',
  'J2S 7S8',
  'Canada',
  '(514) 555-2955',
  '(514) 555-2921',
  None),
 (62,
  'Tarte au sucre',
  29,
  3,
  '48 pies',
  49.3,
  17,
  0,
  0,
  '0',
  29,
  "Forêts d'érables",
  'Chantal Goulet',
  'Accounting Manager',
  '148 rue Chasseur',
  'Ste-Hyacinthe',
  'North America',
  'J2S 7S8',
  'Canada',
  '(514) 555-2955',
  '(514) 555-2921',
  None),
 (63,
  'Vegie-spread',
  7,
  2,
  '15 - 625 g jars',
  43.9,
  24,
  0,
  5,
  '0',
  7,
  'Pavlova, Ltd.',
  'Ian Devling',
  'Marketing Manager',
  '74 Rose St.\nMoonie Ponds',
  'Melbourne',
  'Victoria',
  '3058',
  'Australia',
  '(03) 444-2343',
  '(03) 444-6588',
  None),
 (64,
  'Wimmers gute Semmelknödel',
  12,
  5,
  '20 bags x 4 pieces',
  33.25,
  22,
  80,
  30,
  '0',
  12,
  'Plutzer Lebensmittelgroßmärkte AG',
  'Martin Bein',
  'International Marketing Mgr.',
  'Bogenallee 51',
  'Frankfurt',
  'Western Europe',
  '60439',
  'Germany',
  '(069) 992755',
  None,
  'Plutzer (on the World Wide Web)#http://www.microsoft.com/accessdev/sampleapps/plutzer.htm#'),
 (65,
  'Louisiana Fiery Hot Pepper Sauce',
  2,
  2,
  '32 - 8 oz bottles',
  21.05,
  76,
  0,
  0,
  '0',
  2,
  'New Orleans Cajun Delights',
  'Shelley Burke',
  'Order Administrator',
  'P.O. Box 78934',
  'New Orleans',
  'North America',
  '70117',
  'USA',
  '(100) 555-4822',
  None,
  '#CAJUN.HTM#'),
 (66,
  'Louisiana Hot Spiced Okra',
  2,
  2,
  '24 - 8 oz jars',
  17,
  4,
  100,
  20,
  '0',
  2,
  'New Orleans Cajun Delights',
  'Shelley Burke',
  'Order Administrator',
  'P.O. Box 78934',
  'New Orleans',
  'North America',
  '70117',
  'USA',
  '(100) 555-4822',
  None,
  '#CAJUN.HTM#'),
 (67,
  'Laughing Lumberjack Lager',
  16,
  1,
  '24 - 12 oz bottles',
  14,
  52,
  0,
  10,
  '0',
  16,
  'Bigfoot Breweries',
  'Cheryl Saylor',
  'Regional Account Rep.',
  '3400 - 8th Avenue\nSuite 210',
  'Bend',

In [395]:
query=("""
          SELECT*
          from products AS p
          INNER JOIN suppliers AS s ON s.supplierid=p.supplierid

""")

In [396]:
from sqlalchemy import create_engine

engine = create_engine("sqlite:///data/northwind.db", echo=False)
connection = engine.connect() #para sacar en dataframe
pd.read_sql(query, connection)

,ProductID,ProductName,SupplierID,CategoryID,QuantityPerUnit,UnitPrice,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued,...,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax,HomePage
0,1,Chai,1,1,10 boxes x 20 bags,18.00,39,0,10,0,...,Charlotte Cooper,Purchasing Manager,49 Gilbert St.,London,British Isles,EC1 4SD,UK,(171) 555-2222,None,None
1,2,Chang,1,1,24 - 12 oz bottles,19.00,17,40,25,0,...,Charlotte Cooper,Purchasing Manager,49 Gilbert St.,London,British Isles,EC1 4SD,UK,(171) 555-2222,None,None
2,3,Aniseed Syrup,1,2,12 - 550 ml bottles,10.00,13,70,25,0,...,Charlotte Cooper,Purchasing Manager,49 Gilbert St.,London,British Isles,EC1 4SD,UK,(171) 555-2222,None,None
3,4,Chef Anton's Cajun Seasoning,2,2,48 - 6 oz jars,22.00,53,0,0,0,...,Shelley Burke,Order Administrator,P.O. Box 78934,New Orleans,North America,70117,USA,(100) 555-4822,None,#CAJUN.HTM#
4,5,Chef Anton's Gumbo Mix,2,2,36 boxes,21.35,0,0,0,1,...,Shelley Burke,Order Administrator,P.O. Box 78934,New Orleans,North America,70117,USA,(100) 555-4822,None,#CAJUN.HTM#
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,73,Röd Kaviar,17,8,24 - 150 g jars,15.00,101,0,5,0,...,Michael Björn,Sales Representative,Brovallavägen 231,Stockholm,Northern Europe,S-123 45,Sweden,08-123 45 67,None,None
73,74,Longlife Tofu,4,7,5 kg pkg.,10.00,4,20,5,0,...,Yoshi Nagase,Marketing Manager,9-8 Sekimai\nMusashino-shi,Tokyo,Eastern Asia,100,Japan,(03) 3555-5011,None,None
74,75,Rhönbräu Klosterbier,12,1,24 - 0.5 l bottles,7.75,125,0,25,0,...,Martin Bein,International Marketing Mgr.,Bogenallee 51,Frankfurt,Western Europe,60439,Germany,(069) 992755,None,Plutzer (on the World Wide Web)#http://www.mic...
75,76,Lakkalikööri,23,1,500 ml,18.00,57,0,20,0,...,Anne Heikkonen,Product Manager,Valtakatu 12,Lappeenranta,Scandinavia,53120,Finland,(953) 10956,None,None
76,77,Original Frankfurter grüne Soße,12,2,12 boxes,13.00,32,0,15,0,...,Martin Bein,International Marketing Mgr.,Bogenallee 51,Frankfurt,Western Europe,60439,Germany,(069) 992755,None,Plutzer (on the World Wide Web)#http://www.mic...

In [397]:

query="""
        SELECT region,  cuantos,  suma_precios, suma_precios/cuantos AS precio_promedio
        FROM
                (SELECT region, count(*) AS cuantos, sum(unitprice) AS suma_precios
                FROM products as p
                INNER JOIN suppliers as s ON s.supplierID =p.supplierID
                GROUP BY region
                ORDER BY cuantos DESC);
        """
pd.read_sql(query, connection)

             region  cuantos  suma_precios  precio_promedio
0     North America       16        359.70        22.481250
1    Western Europe       14        722.16        51.582857
2   Southern Europe        7        195.80        27.971429
3   Northern Europe        7        103.75        14.821429
4     British Isles        7        159.70        22.814286
5       Scandinavia        6        114.25        19.041667
6      Eastern Asia        6        182.75        30.458333
7          Victoria        5        177.85        35.570000
8   South-East Asia        3         79.45        26.483333
9               NSW        3         92.80        30.933333
10             None        2         30.00        15.000000
11    South America        1          4.50         4.500000

In [398]:
query=("""
 
              SELECT ((UnitPrice*Quantity)-Discount) as Precio_de_envio, shippeddate
              FROM "order details" AS od
              INNER JOIN orders AS o ON o.orderid=od.orderid
              GROUP BY o.orderid;
       


       """) 

pd.read_sql(query, connection)

       Precio_de_envio          ShippedDate
0               168.00           2016-07-16
1               167.40           2016-07-10
2                77.00           2016-07-12
3               100.75           2016-07-15
4              2591.95           2016-07-11
...                ...                  ...
16277           551.00  2012-12-28 19:03:24
16278           162.00  2022-08-10 08:11:43
16279           882.00  2022-02-23 07:40:46
16280           320.25  2020-04-28 11:21:50
16281           900.00  2023-01-10 09:47:23

[16282 rows x 2 columns]

In [399]:
query=("""
 
              SELECT region, sum((unitprice*quantity)-discount) as dinero_generado, orderdate, city
              FROM invoices
              Group by OrderDate 

       


       """) 

d=pd.read_sql(query, connection)
d

                Region  dinero_generado            OrderDate            City
0        North America         28992.85  2012-07-10 15:40:46          Eugene
1        South America         24589.35  2012-07-10 20:28:57  Rio de Janeiro
2        North America         52573.43  2012-07-11 01:09:16        Portland
3      Northern Europe         23413.40  2012-07-11 20:26:28          Bräcke
4        British Isles         30387.75  2012-07-11 21:17:36          London
...                ...              ...                  ...             ...
15927    North America         34282.53  2023-10-25 13:00:29         Seattle
15928  Southern Europe         60918.66  2023-10-26 06:28:53          Madrid
15929   Western Europe         51375.33  2023-10-27 06:38:44         Leipzig
15930  Southern Europe         27159.69  2023-10-27 18:17:38          Madrid
15931   Western Europe         10959.04  2023-10-28 00:09:48       Bruxelles

[15932 rows x 4 columns]

In [400]:
d

                Region  dinero_generado            OrderDate            City
0        North America         28992.85  2012-07-10 15:40:46          Eugene
1        South America         24589.35  2012-07-10 20:28:57  Rio de Janeiro
2        North America         52573.43  2012-07-11 01:09:16        Portland
3      Northern Europe         23413.40  2012-07-11 20:26:28          Bräcke
4        British Isles         30387.75  2012-07-11 21:17:36          London
...                ...              ...                  ...             ...
15927    North America         34282.53  2023-10-25 13:00:29         Seattle
15928  Southern Europe         60918.66  2023-10-26 06:28:53          Madrid
15929   Western Europe         51375.33  2023-10-27 06:38:44         Leipzig
15930  Southern Europe         27159.69  2023-10-27 18:17:38          Madrid
15931   Western Europe         10959.04  2023-10-28 00:09:48       Bruxelles

[15932 rows x 4 columns]

In [401]:
du=d["City"].unique()
du

array(['Eugene', 'Rio de Janeiro', 'Portland', 'Bräcke', 'London',
       'Albuquerque', 'Cork', 'Buenos Aires', 'Kobenhavn', 'Torino',
       'Marseille', 'Cunewalde', 'Reggio Emilia', 'México D.F.', 'Madrid',
       'Leipzig', 'Sao Paulo', 'Lille', 'Boise', 'I. de Margarita',
       'Barcelona', 'Aachen', 'Lander', 'Lyon', 'Warszawa', None,
       'Charleroi', 'San Francisco', 'Caracas', 'Århus', 'Nantes',
       'Lisboa', 'Köln', 'San Cristóbal', 'Elgin', 'Bern', 'Paris',
       'Barquisimeto', 'Sevilla', 'Oulu', 'Tsawassen', 'Brandenburg',
       'Vancouver', 'München', 'Butte', 'Bruxelles', 'Kirkland', 'Luleå',
       'Stavern', 'Genève', 'Graz', 'Strasbourg', 'Reims', 'Toulouse',
       'Versailles', 'Berlin', 'Stuttgart', 'Seattle', 'Salzburg',
       'Walla Walla', 'Helsinki', 'Cowes', 'Campinas', 'Montréal',
       'Münster', 'Resende', 'Bergamo', 'Anchorage', 'Frankfurt a.M.',
       'Mannheim'], dtype=object)

In [402]:
headers = {
    'User-Agent': 'My User Agent 1.0',
}

latitude={}
longitude={}

for x in du:
    place = x
    address = geocoder.osm(place, headers=headers)
    latitude[x]=address.lat
    longitude[x]=address.lng

latitude

Status code 400 from https://nominatim.openstreetmap.org/search: ERROR - 400 Client Error: Bad Request for url: https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=1

{'Eugene': 44.0505054,
 'Rio de Janeiro': -22.9110137,
 'Portland': 45.5202471,
 'Bräcke': 62.783333,
 'London': 51.4893335,
 'Albuquerque': 35.0841034,
 'Cork': 51.8985136,
 'Buenos Aires': -34.6083696,
 'Kobenhavn': 55.6867243,
 'Torino': 45.0677551,
 'Marseille': 43.2961743,
 'Cunewalde': 51.098481,
 'Reggio Emilia': 44.6086674,
 'México D.F.': 19.3207722,
 'Madrid': 40.4167047,
 'Leipzig': 51.3406321,
 'Sao Paulo': -23.5506507,
 'Lille': 50.6365654,
 'Boise': 43.6166163,
 'I. de Margarita': 11.0205596,
 'Barcelona': 41.3825802,
 'Aachen': 50.776351,
 'Lander': 39.9059878,
 'Lyon': 45.7578137,
 'Warszawa': 52.2337172,
 None: None,
 'Charleroi': 50.4116233,
 'San Francisco': 37.7792588,
 'Caracas': 10.5060934,
 'Århus': 56.1496278,
 'Nantes': 47.2186371,
 'Lisboa': 38.7077507,
 'Köln': 50.938361,
 'San Cristóbal': 17.3156929,
 'Elgin': 42.03726,
 'Bern': 46.9484742,
 'Paris': 48.8588897,
 'Barquisimeto': 10.0774374,
 'Sevilla': 37.3886303,
 'Oulu': 65.0117869,
 'Tsawassen': None,
 'Brandenburg': 52.8455492,
 'Vancouver': 49.2608724,
 'München': 48.1371079,
 'Butte': 39.6519275,
 'Bruxelles': 50.8465573,
 'Kirkland': 47.6765382,
 'Luleå': 65.5831187,
 'Stavern': 52.797273,
 'Genève': 46.2017559,
 'Graz': 47.0708678,
 'Strasbourg': 48.584614,
 'Reims': 49.2577886,
 'Toulouse': 43.6044622,
 'Versailles': 48.8035403,
 'Berlin': 52.510885,
 'Stuttgart': 48.7784485,
 'Seattle': 47.6038321,
 'Salzburg': 47.7981346,
 'Walla Walla': 46.2055155,
 'Helsinki': 60.1674881,
 'Cowes': 50.7633176,
 'Campinas': -22.9056391,
 'Montréal': 45.5031824,
 'Münster': 51.9625101,
 'Resende': -22.4683626,
 'Bergamo': 45.7566557,
 'Anchorage': 61.2163129,
 'Frankfurt a.M.': 50.1106444,
 'Mannheim': 49.4892913}

In [403]:
latitude[None]=34.00
longitude[None]=-40.00

In [404]:
d["Date"]=d["OrderDate"].str[0:7]
d

,Region,dinero_generado,OrderDate,City,Date
0,North America,28992.85,2012-07-10 15:40:46,Eugene,2012-07
1,South America,24589.35,2012-07-10 20:28:57,Rio de Janeiro,2012-07
2,North America,52573.43,2012-07-11 01:09:16,Portland,2012-07
3,Northern Europe,23413.40,2012-07-11 20:26:28,Bräcke,2012-07
4,British Isles,30387.75,2012-07-11 21:17:36,London,2012-07
...,...,...,...,...,...
15927,North America,34282.53,2023-10-25 13:00:29,Seattle,2023-10
15928,Southern Europe,60918.66,2023-10-26 06:28:53,Madrid,2023-10
15929,Western Europe,51375.33,2023-10-27 06:38:44,Leipzig,2023-10
15930,Southern Europe,27159.69,2023-10-27 18:17:38,Madrid,2023-10
15931,Western Europe,10959.04,2023-10-28 00:09:48,Bruxelles,2023-10

In [405]:
d["OrderDate"] = pd.to_datetime(d["OrderDate"],  format='mixed')

d

,Region,dinero_generado,OrderDate,City,Date
0,North America,28992.85,2012-07-10 15:40:46,Eugene,2012-07
1,South America,24589.35,2012-07-10 20:28:57,Rio de Janeiro,2012-07
2,North America,52573.43,2012-07-11 01:09:16,Portland,2012-07
3,Northern Europe,23413.40,2012-07-11 20:26:28,Bräcke,2012-07
4,British Isles,30387.75,2012-07-11 21:17:36,London,2012-07
...,...,...,...,...,...
15927,North America,34282.53,2023-10-25 13:00:29,Seattle,2023-10
15928,Southern Europe,60918.66,2023-10-26 06:28:53,Madrid,2023-10
15929,Western Europe,51375.33,2023-10-27 06:38:44,Leipzig,2023-10
15930,Southern Europe,27159.69,2023-10-27 18:17:38,Madrid,2023-10
15931,Western Europe,10959.04,2023-10-28 00:09:48,Bruxelles,2023-10

In [406]:
latitude

{'Eugene': 44.0505054,
 'Rio de Janeiro': -22.9110137,
 'Portland': 45.5202471,
 'Bräcke': 62.783333,
 'London': 51.4893335,
 'Albuquerque': 35.0841034,
 'Cork': 51.8985136,
 'Buenos Aires': -34.6083696,
 'Kobenhavn': 55.6867243,
 'Torino': 45.0677551,
 'Marseille': 43.2961743,
 'Cunewalde': 51.098481,
 'Reggio Emilia': 44.6086674,
 'México D.F.': 19.3207722,
 'Madrid': 40.4167047,
 'Leipzig': 51.3406321,
 'Sao Paulo': -23.5506507,
 'Lille': 50.6365654,
 'Boise': 43.6166163,
 'I. de Margarita': 11.0205596,
 'Barcelona': 41.3825802,
 'Aachen': 50.776351,
 'Lander': 39.9059878,
 'Lyon': 45.7578137,
 'Warszawa': 52.2337172,
 None: 34.0,
 'Charleroi': 50.4116233,
 'San Francisco': 37.7792588,
 'Caracas': 10.5060934,
 'Århus': 56.1496278,
 'Nantes': 47.2186371,
 'Lisboa': 38.7077507,
 'Köln': 50.938361,
 'San Cristóbal': 17.3156929,
 'Elgin': 42.03726,
 'Bern': 46.9484742,
 'Paris': 48.8588897,
 'Barquisimeto': 10.0774374,
 'Sevilla': 37.3886303,
 'Oulu': 65.0117869,
 'Tsawassen': None,
 'Brandenburg': 52.8455492,
 'Vancouver': 49.2608724,
 'München': 48.1371079,
 'Butte': 39.6519275,
 'Bruxelles': 50.8465573,
 'Kirkland': 47.6765382,
 'Luleå': 65.5831187,
 'Stavern': 52.797273,
 'Genève': 46.2017559,
 'Graz': 47.0708678,
 'Strasbourg': 48.584614,
 'Reims': 49.2577886,
 'Toulouse': 43.6044622,
 'Versailles': 48.8035403,
 'Berlin': 52.510885,
 'Stuttgart': 48.7784485,
 'Seattle': 47.6038321,
 'Salzburg': 47.7981346,
 'Walla Walla': 46.2055155,
 'Helsinki': 60.1674881,
 'Cowes': 50.7633176,
 'Campinas': -22.9056391,
 'Montréal': 45.5031824,
 'Münster': 51.9625101,
 'Resende': -22.4683626,
 'Bergamo': 45.7566557,
 'Anchorage': 61.2163129,
 'Frankfurt a.M.': 50.1106444,
 'Mannheim': 49.4892913}

In [407]:
import datetime

d["year"]=d["OrderDate"].dt.year
d["month"]=d["OrderDate"].dt.month
d["day"]=d["OrderDate"].dt.day


latitude

longitude
print(d["City"])

d["latitud"]=0
d["longuitud"]=0

for x in list(range(15932)):
   d["latitud"].iloc[x]=latitude[(d["City"].iloc[x])]
   d["longuitud"].iloc[x]=longitude[(d["City"].iloc[x])]
   print((d["City"].iloc[x]))



d

0                Eugene
1        Rio de Janeiro
2              Portland
3                Bräcke
4                London
              ...
15927           Seattle
15928            Madrid
15929           Leipzig
15930            Madrid
15931         Bruxelles
Name: City, Length: 15932, dtype: object
Eugene
Rio de Janeiro
Portland
Bräcke
London
London
Albuquerque
Cork
Buenos Aires
Kobenhavn
Torino
Marseille
Cunewalde
Reggio Emilia
México D.F.
Madrid
Leipzig
Marseille
Sao Paulo
Portland
Rio de Janeiro
Lille
México D.F.
Boise
I. de Margarita
Sao Paulo
Barcelona
London
Aachen
Reggio Emilia
México D.F.
Lander
Lyon
Lyon
Warszawa
Cunewalde
Lyon
None
Charleroi
San Francisco
Caracas
London
None
Århus
Madrid
México D.F.
Nantes
México D.F.
Lyon
Sao Paulo
Aachen
Reggio Emilia
Lisboa
Reggio Emilia
None
Sao Paulo
Buenos Aires
Köln
Buenos Aires
London
San Cristóbal
Elgin
Bern
Barcelona
Rio de Janeiro
Leipzig
Sao Paulo
Paris
Barquisimeto
Bern
London
Nantes
Sevilla
México D.F.
Oulu
Tsawassen
Barcelona
Buenos Aires
Brandenburg
Lander
None
Caracas
Vancouver
Bern
Leipzig
Aachen
München
Vancouver
Butte
Bruxelles
None
Kirkland
London
Luleå
Buenos Aires
Sao Paulo
Vancouver
Paris
San Cristóbal
Madrid
Madrid
Elgin
Stavern
Caracas
Genève
London
I. de Margarita
London
I. de Margarita
Nantes
Boise
Rio de Janeiro
München
Madrid
Barquisimeto
Nantes
San Cristóbal
Leipzig
Graz
Strasbourg
Sevilla
München
Madrid
London
México D.F.
San Francisco
Luleå
Reims
Bräcke
Warszawa
Lille
Madrid
Toulouse
Reggio Emilia
Bräcke
Kobenhavn
Nantes
None
London
Paris
Toulouse
México D.F.
Reggio Emilia
Buenos Aires
Leipzig
Versailles
Sao Paulo
Rio de Janeiro
Reims
Berlin
None
Boise
Stuttgart
Seattle
Marseille
Madrid
Cork
Brandenburg
Warszawa
I. de Margarita
Reggio Emilia
Bruxelles
Rio de Janeiro
Bruxelles
Bruxelles
Lyon
Kobenhavn
Madrid
Lander
Köln
Rio de Janeiro
Lille
Salzburg
San Cristóbal
Marseille
London
Sao Paulo
Sao Paulo
Luleå
Lille
Lille
None
Reggio Emilia
Kobenhavn
México D.F.
Barcelona
San Cristóbal
London
Seattle
Berlin
San Francisco
Versailles
Eugene
Genève
London
Paris
Buenos Aires
México D.F.
Barquisimeto
Tsawassen
Marseille
Paris
Madrid
Nantes
Brandenburg
Stavern
None
Madrid
Boise
Reims
Walla Walla
Toulouse
Sao Paulo
Lisboa
Paris
Sao Paulo
Butte
Paris
Berlin
None
México D.F.
México D.F.
Cunewalde
Helsinki
Cowes
Charleroi
Kirkland
Portland
Strasbourg
Sao Paulo
Campinas
Montréal
Cowes
Sao Paulo
Sao Paulo
México D.F.
Madrid
Barquisimeto
Reggio Emilia
Marseille
Portland
Sevilla
Sevilla
I. de Margarita
Lisboa
Lisboa
Nantes
San Cristóbal
München
Sevilla
Münster
Lille
Kobenhavn
Nantes
Cork
Bräcke
Caracas
Cowes
Stavern
Paris
Bern
Stavern
Charleroi
Sao Paulo
Caracas
Vancouver
Bruxelles
Resende
Bruxelles
Portland
Sevilla
Cork
Genève
Graz
Elgin
London
Paris
Seattle
Paris
Walla Walla
Madrid
México D.F.
Sao Paulo
Oulu
Sao Paulo
Stavern
Montréal
Barquisimeto
Bergamo
Vancouver
Madrid
Torino
Rio de Janeiro
Oulu
None
Sao Paulo
Anchorage
Buenos Aires
Sao Paulo
Paris
London
Campinas
Luleå
México D.F.
Århus
London
México D.F.
México D.F.
Leipzig
Strasbourg
Vancouver
Kobenhavn
Versailles
Sao Paulo
Eugene
Strasbourg
Cunewalde
Bruxelles
Rio de Janeiro
Lyon
London
London
Paris
Cunewalde
Sao Paulo
Madrid
Bergamo
München
Toulouse
Berlin
México D.F.
None
Sevilla
Boise
London
Cork
Frankfurt a.M.
Münster
Resende
Lisboa
Lille
Stuttgart
Butte
Bern
Rio de Janeiro
Campinas
Warszawa
Sao Paulo
London
Albuquerque
Graz
Barquisimeto
México D.F.
Rio de Janeiro
London
Bräcke
Rio de Janeiro
Elgin
None
Campinas
Albuquerque
Sao Paulo
Reggio Emilia
Sevilla
Buenos Aires
Albuquerque
London
Strasbourg
Cowes
Stuttgart
Kirkland
Madrid
Kirkland
San Cristóbal
Resende
I. de Margarita
México D.F.
Bruxelles
Toulouse
Rio de Janeiro
Helsinki
Portland
Lander
London
Leipzig
Cork
Rio de Janeiro
Genève
México D.F.
Toulouse
Vancouver
Lisboa
Lille
Luleå
None
München
London
Madrid
Nantes
Bräcke
Campinas
Elgin
Helsinki
London
Frankfurt a.M.
London
Butte
Torino
Rio de Janeiro
Aachen
Rio de Janeiro
Rio de Janeiro
London
Albuquerque
Butte
Kirkland
Madrid
Frankfurt a.M.
Resende
Lisboa
Rio de Janeiro
Rio de Janeiro
London
Mannheim
Århus
Marseille
Sao Paulo
Madrid
I. de Margarita
Seattle
San Cristóbal
Frankfurt a.M.
Genève
Sevilla
Albuquerque
Boise
Bern
San Francisco
Leipzig
London
Leipzig
Rio de Janeiro
Anchorage
München
Luleå
Lyon
Cunewalde
Portland
Cork
Buenos Aires
Paris
Barcelona
London
Bergamo
Boise
Vancouver
Bergamo
Eugene
Sevilla
Bräcke
Buenos Aires
Nantes
Portland
Sao Paulo
Montréal
Buenos Aires
Versailles
Genève
London
Tsawassen
London
Mannheim
Lisboa
Paris
Buenos Aires
München
Sao Paulo
Århus
Nantes
Madrid
Madrid
San Cristóbal
Madrid
Rio de Janeiro
Resende
Campinas
Bergamo
Strasbourg
Lisboa
Stuttgart
Albuquerque
Frankfurt a.M.
Århus
Rio de Janeiro
Paris
Oulu
London
Campinas
None
Anchorage
Madrid
Salzburg
Kirkland
Kobenhavn
Stuttgart
Buenos Aires
Helsinki
Köln
Stuttgart
Rio de Janeiro
Buenos Aires
Mannheim
Genève
Elgin
Bern
Köln
Cunewalde
London
Torino
Rio de Janeiro
Bruxelles
Mannheim
Buenos Aires
Anchorage
Cowes
Aachen
Rio de Janeiro
Leipzig
Barquisimeto
Leipzig
Genève
Eugene
México D.F.
Toulouse
Paris
London
México D.F.
Reims
Bern
Sao Paulo
Lyon
London
Versailles
Sevilla
San Cristóbal
Barquisimeto
Versailles
Lisboa
Lisboa
Walla Walla
México D.F.
Aachen
San Cristóbal
Kobenhavn
Sao Paulo
Anchorage
México D.F.
Caracas
Rio de Janeiro
Portland
Buenos Aires
Madrid
London
Reggio Emilia
Sao Paulo
San Francisco
Marseille
Köln
Albuquerque
Reims
Cunewalde
Aachen
Münster
Warszawa
None
Toulouse
London
Lisboa
Reims
Rio de Janeiro
None
Versailles
Sevilla
Toulouse
London
Oulu
London
Münster
Salzburg
Leipzig
London
Berlin
Paris
Graz
Madrid
Berlin
Butte
México D.F.
Münster
Leipzig
Torino
Montréal
Sao Paulo
London
Madrid
London
Kirkland
Leipzig
Toulouse
London
Rio de Janeiro
London
Lille
Lisboa
London
Resende
Caracas
San Cristóbal
Brandenburg
Versailles
Anchorage
Bergamo
Campinas
Albuquerque
Campinas
Campinas
Brandenburg
Montréal
Sao Paulo
London
Seattle
None
Bergamo
London
San Cristóbal
Barquisimeto
Tsawassen
Aachen
Münster
Buenos Aires
Rio de Janeiro
Brandenburg
Montréal
Warszawa
Lander
Genève
Bern
Sao Paulo
Reims
Seattle
Elgin
Tsawassen
Seattle
Buenos Aires
Bergamo
Eugene
Buenos Aires
Leipzig
Helsinki
Kobenhavn
Sao Paulo
München
Luleå
Kobenhavn
Mannheim
Sao Paulo
Münster
Helsinki
Montréal
Brandenburg
Resende
Reggio Emilia
México D.F.
Berlin
Vancouver
Münster
Graz
Berlin
Madrid
Luleå
Toulouse
México D.F.
Bergamo
Buenos Aires
México D.F.
México D.F.
Bergamo
Lille
Barquisimeto
Campinas
Köln
Marseille
Walla Walla
Bergamo
Lander
Kirkland
Seattle
Kirkland
México D.F.
I. de Margarita
Stuttgart
Rio de Janeiro
London
Versailles
Lisboa
Sao Paulo
Köln
Warszawa
Anchorage
Sevilla
Eugene
Lisboa
Graz
Lille
Walla Walla
Bruxelles
Bern
Lisboa
Albuquerque
San Francisco
Strasbourg
None
None
Barquisimeto
Montréal
Paris
Rio de Janeiro
México D.F.
Lyon
Cunewalde
Anchorage
Sao Paulo
Reggio Emilia
Münster
Seattle
Marseille
San Francisco
Resende
Buenos Aires
London
Rio de Janeiro
Lille
München
München
Cork
Portland
México D.F.
Rio de Janeiro
Århus
México D.F.
Buenos Aires
Portland
Buenos Aires
San Francisco
Portland
Anchorage
Bern
Warszawa
Aachen
None
Nantes
Köln
Vancouver
Leipzig
London
Montréal
Buenos Aires
London
Kirkland
Stuttgart
Lander
London
Walla Walla
Madrid
México D.F.
México D.F.
Madrid
Stavern
Charleroi
Barcelona
None
Eugene
Buenos Aires
Sao Paulo
London
Graz
Reggio Emilia
London
Resende
Eugene
Frankfurt a.M.
Leipzig
México D.F.
Aachen
Bruxelles
London
Torino
Reggio Emilia
Nantes
Charleroi
Århus
London
Lyon
México D.F.
Elgin
Berlin
Buenos Aires
Mannheim
México D.F.
Campinas
I. de Margarita
Warszawa
Madrid
Elgin
Nantes
Elgin
Lisboa
Torino
San Francisco
México D.F.
Stavern
Graz
Marseille
Seattle
Madrid
Luleå
Rio de Janeiro
Walla Walla
Sao Paulo
Sao Paulo
Anchorage
Marseille
San Cristóbal
Lille
Århus
Vancouver
Anchorage
Eugene
México D.F.
Walla Walla
Bern
Bergamo
Lander
San Cristóbal
Barcelona
None
Torino
Frankfurt a.M.
Strasbourg
Rio de Janeiro
Seattle
Buenos Aires
Elgin
Leipzig
Montréal
Resende
Rio de Janeiro
Bruxelles
Buenos Aires
México D.F.
Kobenhavn
Salzburg
Mannheim
Cunewalde
Sao Paulo
Charleroi
Sao Paulo
Albuquerque
London
Rio de Janeiro
Barquisimeto
Graz
Vancouver
Mannheim
Cowes
Stavern
Nantes
Mannheim
Lille
Salzburg
México D.F.
Caracas
Genève
Cunewalde
Butte
Lyon
Sao Paulo
Caracas
Lille
Bruxelles
Bräcke
London
Caracas
Sao Paulo
Bräcke
México D.F.
Nantes
Strasbourg
Salzburg
Warszawa
México D.F.
Lander
Sao Paulo
London
Tsawassen
Boise
Tsawassen
Albuquerque
Elgin
Sao Paulo
Nantes
Tsawassen
Helsinki
Marseille
Graz
Caracas
Eugene
Lander
Portland
Cork
Münster
Oulu
San Cristóbal
Seattle
Charleroi
Madrid
Versailles
Luleå
London
London
None
Nantes
London
Köln
Paris
Stavern
Walla Walla
Lisboa
Seattle
Caracas
Sao Paulo
Mannheim
Strasbourg
Lisboa
London
Toulouse
None
London
Lille
Stuttgart
Albuquerque
Charleroi
London
Buenos Aires
Nantes
Lyon
Walla Walla
Luleå
Lyon
Toulouse
Barquisimeto
Paris
Sevilla
Stuttgart
Marseille
Lille
Lander
Lander
Stavern
Berlin
Boise
Leipzig
Buenos Aires
London
Luleå
Brandenburg
Bergamo
Eugene
Tsawassen
Paris
Sao Paulo
London
Brandenburg
Sevilla
Lander
Aachen
Resende
Helsinki
Nantes
Madrid
Montréal
None
México D.F.
Eugene
Boise
Salzburg
Cunewalde
London
Buenos Aires
Nantes
Stavern
I. de Margarita
México D.F.
Barquisimeto
Kirkland
Lyon
London
Rio de Janeiro
Buenos Aires
Torino
Portland
Cowes
Reggio Emilia
Münster
Strasbourg
Helsinki
Lander
Bern
Graz
Cowes
Eugene
Brandenburg
Graz
Portland
Berlin
Bräcke
Montréal
México D.F.
Lyon
Lille
Madrid
Butte
Lille
None
Rio de Janeiro
Madrid
Caracas
Cork
Barquisimeto
México D.F.
Buenos Aires
San Cristóbal
México D.F.
Portland
Paris
Århus
San Francisco
Tsawassen
México D.F.
Resende
London
Torino
Kobenhavn
Salzburg
London
Genève
Walla Walla
Versailles
London
Anchorage
San Francisco
Lisboa
Paris
San Francisco
London
Stuttgart
Versailles
Bräcke
Köln
Paris
Sao Paulo
Stavern
Bräcke
Rio de Janeiro
Versailles
Campinas
México D.F.
Barcelona
Torino
Lille
Butte
Graz
London
Torino
Lander
Sao Paulo
Madrid
Oulu
Eugene
México D.F.
Campinas
Buenos Aires
None
Portland
Köln
Seattle
Kirkland
Luleå
Frankfurt a.M.
Versailles
Campinas
Buenos Aires
London
Reggio Emilia
Lisboa
Walla Walla
Boise
San Francisco
México D.F.
México D.F.
Münster
None
Buenos Aires
Albuquerque
Madrid
Århus
Stavern
Boise
Madrid
Torino
Tsawassen
Cowes
Genève
London
Portland
London
Luleå
London
Oulu
Albuquerque
Brandenburg
Eugene
Walla Walla
Buenos Aires
None
Versailles
Strasbourg
Charleroi
Lille
Reims
Montréal
London
San Francisco
Reims
Cork
México D.F.
London
Sao Paulo
Torino
Versailles
Barquisimeto
Warszawa
Butte
Stuttgart
San Francisco
México D.F.
México D.F.
Marseille
London
Eugene
Portland
Elgin
Helsinki
Cowes
Graz
Buenos Aires
Sevilla
Cork
Sao Paulo
Salzburg
Graz
Torino
None
Campinas
Boise
Bern
Cunewalde
Reggio Emilia
Lisboa
Kirkland
Reggio Emilia
México D.F.
Genève
Vancouver
Barquisimeto
Lisboa
Köln
Lander
Bergamo
México D.F.
Brandenburg
Paris
Sao Paulo
Vancouver
Bräcke
Buenos Aires
Portland
Elgin
Vancouver
Vancouver
London
México D.F.
Versailles
Resende
Strasbourg
Helsinki
Lisboa
Rio de Janeiro
Cork
Mannheim
Århus
Bruxelles
Resende
Sao Paulo
Paris
San Francisco
I. de Margarita
Stavern
Rio de Janeiro
México D.F.
Brandenburg
Berlin
México D.F.
Walla Walla
Rio de Janeiro
London
Portland
Sao Paulo
Strasbourg
Madrid
Rio de Janeiro
Graz
México D.F.
Elgin
Aachen
Sao Paulo
München
Bruxelles
Sevilla
Vancouver
Lisboa
Paris
Cunewalde
Bern
Graz
Tsawassen
Toulouse
Stuttgart
Charleroi
Brandenburg
Boise
None
Cowes
Luleå
Genève
Rio de Janeiro
Salzburg
Caracas
Elgin
Nantes
Mannheim
Buenos Aires
London
Montréal
Sao Paulo
Oulu
Aachen
Salzburg
Paris
Resende
San Francisco
Cork
Albuquerque
Münster
Walla Walla
Eugene
London
Montréal
Graz
Lander
Brandenburg
Rio de Janeiro
Berlin
Helsinki
Caracas
Lisboa
México D.F.
Boise
Seattle
México D.F.
México D.F.
Lyon
London
London
Paris
Charleroi
Vancouver
Eugene
Madrid
Lisboa
Lisboa
Cork
Sao Paulo
Caracas
Århus
Cunewalde
Albuquerque
Reims
Eugene
Sevilla
Sao Paulo
Butte
Cowes
Madrid
Sao Paulo
Madrid
Eugene
Buenos Aires
Berlin
Lisboa
Münster
Elgin
Buenos Aires
México D.F.
Salzburg
Butte
Rio de Janeiro
Butte
Århus
Torino
Leipzig
México D.F.
London
Seattle
Köln
London
Brandenburg
Sao Paulo
Madrid
None
Mannheim
Versailles
Frankfurt a.M.
Leipzig
Madrid
Lisboa
Seattle
Rio de Janeiro
London
Buenos Aires
Bern
Madrid
Campinas
Lander
Stavern
London
Genève
México D.F.
Warszawa
Eugene
Bräcke
San Francisco
Sao Paulo
Graz
Bergamo
Nantes
Madrid
Stavern
Salzburg
Graz
México D.F.
Paris
Lander
México D.F.
Campinas
Elgin
San Francisco
Sao Paulo
Eugene
Reggio Emilia
London
México D.F.
London
Salzburg
Lander
Montréal
Seattle
London
Nantes
London
Boise
Eugene
London
Stuttgart
Seattle
Barquisimeto
Montréal
Cork
Lille
Luleå
Helsinki
Barquisimeto
None
Strasbourg
Montréal
Sevilla
Buenos Aires
Cork
Resende
London
Torino
Nantes
Albuquerque
Rio de Janeiro
Reggio Emilia
Kirkland
Charleroi
None
Buenos Aires
Portland
Buenos Aires
Albuquerque
Brandenburg
Kobenhavn
London
I. de Margarita
Strasbourg
Salzburg
San Cristóbal
Cowes
Rio de Janeiro
Madrid
Madrid
Oulu
London
Århus
I. de Margarita
San Cristóbal
Cunewalde
Sevilla
Strasbourg
Stuttgart
Brandenburg
Madrid
México D.F.
Sevilla
México D.F.
Brandenburg
Montréal
Lisboa
Madrid
Bräcke
Strasbourg
Tsawassen
Rio de Janeiro
Montréal
Sao Paulo
London
Walla Walla
London
Rio de Janeiro
Toulouse
Resende
Århus
México D.F.
Bern
Sao Paulo
Elgin
Bruxelles
Oulu
Elgin
Sao Paulo
London
Rio de Janeiro
London
Sao Paulo
Butte
Sao Paulo
Luleå
Aachen
México D.F.
Montréal
None
Madrid
Resende
Brandenburg
Bräcke
Paris
Luleå
México D.F.
Campinas

C:\Users\unaif\AppData\Local\Temp\ipykernel_34768\3689865394.py:17: FutureWarning:

ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


C:\Users\unaif\AppData\Local\Temp\ipykernel_34768\3689865394.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\unaif\AppData\Local\Temp\ipykernel_34768\3689865394.py:17: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '44.0505054' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

C:\Users\unaif\AppData\Local\Temp\ipykernel_34768\3689865394.py:18: FutureWarning:

ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


C:\Users\unaif\AppData\Local\Temp\ipykernel_34768\3689865394.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\unaif\AppData\Local\Temp\ipykernel_34768\3689865394.py:18: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-123.0950506' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.

C:\Users\unaif\AppData\Local\Temp\ipykernel_34768\3689865394.py:17: FutureWarning:

ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


C:\Users\unaif\AppData\Local\Temp\ipykernel_34768\3689865394.py:18: FutureWarning:

ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Reggio Emilia
México D.F.
Seattle
Barquisimeto
Sao Paulo
Torino
Lyon
Sao Paulo
Graz
London
Bern
München
Münster
Strasbourg
Albuquerque
None
Toulouse
Barquisimeto
Nantes
México D.F.
Vancouver
Madrid
Rio de Janeiro
Sao Paulo
Lisboa
Luleå
Luleå
Resende
Sao Paulo
Sao Paulo
Bräcke
London
Reims
Stavern
Seattle
Lisboa
Kirkland
Rio de Janeiro
Madrid
Madrid
San Cristóbal
Sao Paulo
Cork
Eugene
San Cristóbal
Vancouver
Elgin
Aachen
Genève
Rio de Janeiro
México D.F.
London
Paris
Seattle
Århus
Cunewalde
Rio de Janeiro
Sao Paulo
Paris
Buenos Aires
Genève
Butte
Madrid
Walla Walla
Stuttgart
Warszawa
Warszawa
San Cristóbal
Sao Paulo
London
Rio de Janeiro
London
Paris
London
Kirkland
Kobenhavn
Portland
None
Kobenhavn
Tsawassen
San Francisco
Tsawassen
Torino
Warszawa
Kobenhavn
Seattle
Graz
Lille
Buenos Aires
Oulu
Eugene
Reggio Emilia
Rio de Janeiro
Graz
Aachen
Frankfurt a.M.
Reims
Walla Walla
Walla Walla
Bergamo
Reims
Graz
Anchorage
Kobenhavn
Buenos Aires
Strasbourg
San Cristóbal
Bergamo
Caracas
I. de Margarita
Torino
San Cristóbal
Madrid
Berlin
London
Cork
None
München
Charleroi
Münster
Warszawa
Lisboa
Luleå
México D.F.
Boise
Sao Paulo
Marseille
Lyon
Cunewalde
Barquisimeto
Madrid
Mannheim
Lisboa
Bruxelles
Köln
Warszawa
Lisboa
Barquisimeto
México D.F.
Graz
Campinas
Toulouse
Århus
Reggio Emilia
San Cristóbal
London
Warszawa
Bruxelles
Buenos Aires
Frankfurt a.M.
Bräcke
Eugene
London
Cork
Nantes
Münster
Madrid
Bergamo
Cork
Leipzig
Nantes
México D.F.
Stavern
Madrid
Toulouse
Bern
London
Versailles
Rio de Janeiro
Campinas
Leipzig
Caracas
Madrid
Sevilla
México D.F.
Caracas
Münster
Nantes
Buenos Aires
Butte
Lander
Boise
Aachen
Sao Paulo
Paris
México D.F.
Versailles
Torino
Anchorage
None
Walla Walla
Rio de Janeiro
Berlin
Elgin
Tsawassen
Rio de Janeiro
Nantes
Vancouver
Tsawassen
Kobenhavn
Butte
London
Paris
Rio de Janeiro
Luleå
Rio de Janeiro
Lisboa
México D.F.
London
Tsawassen
Luleå
München
Aachen
Cowes
London
Eugene
Warszawa
Stuttgart
Boise
Lyon
Nantes
Madrid
Kobenhavn
México D.F.
Rio de Janeiro
Sao Paulo
Köln
Nantes
Madrid
Walla Walla
Berlin
Reims
Buenos Aires
Lander
Stuttgart
Graz
Aachen
Luleå
London
Sao Paulo
Genève
Sao Paulo
München
Cowes
San Francisco
Seattle
Madrid
México D.F.
Århus
Madrid
London
Lille
Buenos Aires
Butte
London
Vancouver
Reims
Madrid
Bräcke
Münster
Sao Paulo
Madrid
Anchorage
Rio de Janeiro
Bern
Bern
Tsawassen
Albuquerque
Paris
Lisboa
Lille
Paris
Portland
Rio de Janeiro
Århus
Cowes
Bergamo
Leipzig
Seattle
Marseille
Buenos Aires
Cunewalde
London
Nantes
Montréal
Butte
Caracas
México D.F.
San Cristóbal
Buenos Aires
Boise
London
Buenos Aires
Barcelona
None
Reggio Emilia
Nantes
Bruxelles
None
Århus
None
Århus
Genève
Oulu
Rio de Janeiro
Reims
Toulouse
Lille
Cowes
Eugene
London
Kobenhavn
Sao Paulo
Walla Walla
Montréal
Lille
Campinas
Caracas
Kobenhavn
Walla Walla
Vancouver
Genève
Walla Walla
Charleroi
Lille
Resende
Bräcke
London
I. de Margarita
London
Montréal
Buenos Aires
Frankfurt a.M.
Sevilla
Portland
Sao Paulo
Rio de Janeiro
Warszawa
München
Aachen
London
Barquisimeto
Walla Walla
Århus
San Cristóbal
Eugene
Aachen
Berlin
London
Marseille
San Francisco
Köln
San Francisco
Sevilla
Mannheim
München
Madrid
London
México D.F.
Caracas
I. de Margarita
Albuquerque
San Cristóbal
Århus
Barquisimeto
London
Rio de Janeiro
Anchorage
Cunewalde
Barquisimeto
Buenos Aires
London
Rio de Janeiro
Rio de Janeiro
Campinas
Stuttgart
Portland
Butte
Bern
I. de Margarita
Rio de Janeiro
London
Kirkland
Sao Paulo
Lander
Luleå
Buenos Aires
Stavern
Portland
Bern
Lisboa
Seattle
Strasbourg
Charleroi
Lisboa
Rio de Janeiro
Frankfurt a.M.
Nantes
Rio de Janeiro
None
Nantes
Berlin
Paris
Sao Paulo
None
Sao Paulo
San Francisco
Elgin
Bräcke
London
Rio de Janeiro
Portland
Rio de Janeiro
Anchorage
Madrid
Vancouver
Caracas
Luleå
México D.F.
Stuttgart
Oulu
Reims
México D.F.
Mannheim
London
Cunewalde
None
Marseille
Eugene
México D.F.
Portland
Resende
Portland
México D.F.
Genève
Rio de Janeiro
Campinas
Toulouse
Butte
Anchorage
Anchorage
Portland
I. de Margarita
Rio de Janeiro
Elgin
Rio de Janeiro
Eugene
Anchorage
Sao Paulo
Lille
Cork
Sao Paulo
Lisboa
México D.F.
San Francisco
Nantes
Cowes
Kirkland
Barquisimeto
Brandenburg
Rio de Janeiro
Portland
Rio de Janeiro
Anchorage
Versailles
Reggio Emilia
Kirkland
Barcelona
Resende
Frankfurt a.M.
I. de Margarita
Sevilla
Luleå
Bergamo
Münster
Barquisimeto
México D.F.
London
Versailles
Cunewalde
Cowes
London
Rio de Janeiro
Anchorage
Eugene
México D.F.
Caracas
London
Mannheim
Berlin
Versailles
Kobenhavn
Paris
Torino
Reims
Genève
Eugene
Butte
Barquisimeto
Bruxelles
Bräcke
None
Resende
Sao Paulo
Paris
México D.F.
I. de Margarita
Portland
London
Oulu
Rio de Janeiro
Rio de Janeiro
Stavern
Buenos Aires
Luleå
Nantes
Albuquerque
Lille
Cork
Elgin
London
Aachen
London
London
Strasbourg
Barcelona
Boise
San Francisco
London
Cowes
Köln
Portland
Genève
Elgin
Rio de Janeiro
Münster
México D.F.
Genève
Stavern
Helsinki
Walla Walla
Münster
Campinas
Seattle
Elgin
Genève
Lille
London
Stuttgart
Marseille
Walla Walla
Cork
Lander
Seattle
Kirkland
Strasbourg
Frankfurt a.M.
London
None
Rio de Janeiro
Portland
Campinas
Barcelona
Sao Paulo
Leipzig
Albuquerque
Sao Paulo
San Francisco
Portland
Brandenburg
Sao Paulo
London
Frankfurt a.M.
I. de Margarita
Kirkland
Portland
Vancouver
München
Campinas
Butte
México D.F.
Butte
Kirkland
México D.F.
Albuquerque
London
Sao Paulo
San Cristóbal
Eugene
Rio de Janeiro
Resende
Paris
Marseille
Caracas
Lille
Kobenhavn
Caracas
Mannheim
Bräcke
Versailles
Lyon
Barcelona
San Francisco
Nantes
Sao Paulo
Warszawa
Århus
Madrid
Helsinki
Campinas
Lille
Lisboa
München
Campinas
Anchorage
México D.F.
Strasbourg
Nantes
Toulouse
Sao Paulo
Graz
Torino
Kobenhavn
Seattle
Elgin
London
Portland
London
London
Cork
Versailles
Lisboa
Münster
Genève
México D.F.
Montréal
Albuquerque
None
Sevilla
Lisboa
Köln
Frankfurt a.M.
México D.F.
Sao Paulo
None
Paris
Köln
Oulu
Kirkland
Albuquerque
Nantes
Buenos Aires
Cunewalde
México D.F.
London
Albuquerque
Boise
None
Caracas
Lisboa
Torino
Bräcke
Seattle
None
Århus
Bergamo
Boise
México D.F.
Boise
Sao Paulo
Strasbourg
Århus
Buenos Aires
Torino
Butte
Genève
Walla Walla
Buenos Aires
Stavern
Madrid
Lisboa
Genève
México D.F.
Aachen
Versailles
Eugene
Rio de Janeiro
Århus
Madrid
Strasbourg
Leipzig
Bergamo
None
Lisboa
México D.F.
London
Portland
Marseille
México D.F.
Bergamo
Butte
Warszawa
Bruxelles
Versailles
Bruxelles
Kirkland
Madrid
Kirkland
Cowes
Toulouse
Cork
Sao Paulo
México D.F.
Buenos Aires
Madrid
Kobenhavn
Warszawa
Lisboa
Graz
Torino
Cowes
Helsinki
Montréal
San Francisco
London
Resende
Kirkland
Oulu
Rio de Janeiro
Barquisimeto
London
Oulu
Barquisimeto
Salzburg
London
Cork
Cowes
Caracas
London
Salzburg
Lisboa
Aachen
Nantes
Buenos Aires
Portland
Nantes
Barquisimeto
Münster
Oulu
San Francisco
Lille
Sao Paulo
Lille
Rio de Janeiro
México D.F.
Butte
Warszawa
Cunewalde
Lille
London
Lisboa
Lille
Luleå
México D.F.
Sevilla
London
London
Caracas
Tsawassen
Århus
Cunewalde
Marseille
Vancouver
San Cristóbal
Madrid
Kirkland
Graz
Aachen
Barcelona
Vancouver
Frankfurt a.M.
London
Rio de Janeiro
Cork
Helsinki
London
London
Münster
Cork
Århus
Seattle
Butte
Münster
Bruxelles
Vancouver
México D.F.
Resende
Mannheim
Sao Paulo
Caracas
London
Eugene
London
Torino
Helsinki
Portland
Stuttgart
Anchorage
Buenos Aires
Cork
Aachen
Madrid
None
Portland
México D.F.
Lille
Reggio Emilia
Nantes
Strasbourg
Mannheim
Aachen
Leipzig
Versailles
Kirkland
Reims
Strasbourg
Bruxelles
Butte
Strasbourg
Caracas
Lyon
Brandenburg
Vancouver
Paris
Buenos Aires
Reims
Köln
London
Lisboa
London
Toulouse
Buenos Aires
Frankfurt a.M.
Nantes
Albuquerque
Frankfurt a.M.
Cork
Marseille
Madrid
Tsawassen
Barquisimeto
Sao Paulo
Helsinki
San Francisco
México D.F.
Montréal
Buenos Aires
Lyon
Charleroi
Eugene
Rio de Janeiro
Barquisimeto
Bräcke
Kirkland
San Cristóbal
Sao Paulo
Münster
Torino
Madrid
Bern
Buenos Aires
Eugene
Rio de Janeiro
Barquisimeto
Stavern
Buenos Aires
Paris
Leipzig
Lyon
Vancouver
Elgin
Reggio Emilia
Reggio Emilia
Bern
London
Eugene
London
Århus
Albuquerque
Eugene
Sao Paulo
México D.F.
Aachen
Rio de Janeiro
Lisboa
Leipzig
Resende
Bern
México D.F.
Buenos Aires
London
Sao Paulo
Paris
Barcelona
London
Portland
Bergamo
Elgin
Cowes
Tsawassen
Kobenhavn
Lisboa
Sao Paulo
México D.F.
Madrid
Warszawa
Madrid
Frankfurt a.M.
Walla Walla
Barcelona
Nantes
London
None
Genève
Nantes
Elgin
Mannheim
Paris
Walla Walla
Cowes
Mannheim
Boise
Århus
Bern
México D.F.
Reims
México D.F.
London
Charleroi
Luleå
Buenos Aires
México D.F.
Barcelona
Buenos Aires
Paris
Rio de Janeiro
Genève
Bergamo
México D.F.
London
México D.F.
Graz
Kirkland
Portland
Portland
Reggio Emilia
México D.F.
Sao Paulo
Århus
Nantes
Köln
Berlin
Toulouse
México D.F.
Stuttgart
Buenos Aires
Bruxelles
Tsawassen
London
Portland
Paris
Århus
Cowes
Bergamo
I. de Margarita
Luleå
México D.F.
Sao Paulo
Marseille
Seattle
Berlin
San Cristóbal
Mannheim
Lisboa
I. de Margarita
Köln
Cunewalde
Sao Paulo
Lisboa
Barcelona
Montréal
Campinas
Tsawassen
None
Reims
México D.F.
Salzburg
Bergamo
Elgin
Torino
Strasbourg
Sao Paulo
London
Boise
Albuquerque
Boise
Bruxelles
Stuttgart
Lyon
Kobenhavn
Eugene
Walla Walla
Reims
Barcelona
Buenos Aires
Elgin
Stuttgart
Barquisimeto
Lille
Cowes
Resende
Rio de Janeiro
Anchorage
Münster
Luleå
Butte
Buenos Aires
San Cristóbal
Nantes
Salzburg
Resende
Brandenburg
Århus
Eugene
Buenos Aires
London
London
Seattle
Sao Paulo
Charleroi
Lisboa
Marseille
Marseille
México D.F.
Bruxelles
Århus
San Francisco
Sevilla
Helsinki
Oulu
Lille
Leipzig
Nantes
Frankfurt a.M.
Salzburg
Caracas
Boise
Sao Paulo
Brandenburg
Portland
México D.F.
Nantes
London
Lander
Münster
Versailles
Nantes
London
Aachen
Münster
Århus
Nantes
Bern
Resende
Aachen
München
Tsawassen
Nantes
Berlin
Oulu
I. de Margarita
Graz
Rio de Janeiro
Aachen
Vancouver
Eugene
Sao Paulo
Portland
London
Warszawa
Elgin
Portland
Sao Paulo
Lyon
Helsinki
Reggio Emilia
Bergamo
Kirkland
Bruxelles
Rio de Janeiro
México D.F.
Charleroi
México D.F.
México D.F.
Bräcke
Sao Paulo
Cork
Genève
Sevilla
Paris
Barquisimeto
México D.F.
Charleroi
Cowes
Paris
Seattle
Kobenhavn
San Cristóbal
Marseille
None
Resende
Cowes
Paris
Bergamo
Leipzig
Campinas
Lille
Paris
Mannheim
Cowes
Caracas
Barquisimeto
Bräcke
Toulouse
México D.F.
Genève
Boise
None
Lisboa
Madrid
Graz
Butte
Resende
México D.F.
Leipzig
Rio de Janeiro
México D.F.
Berlin
Nantes
Toulouse
Eugene
Lyon
Warszawa
Madrid
Stuttgart
Rio de Janeiro
Luleå
Stuttgart
Resende
Anchorage
Sao Paulo
Kirkland
Mannheim
Stuttgart
Portland
Resende
Resende
Lille
Warszawa
London
Paris
Oulu
Sao Paulo
Elgin
London
México D.F.
Helsinki
Montréal
Sao Paulo
Frankfurt a.M.
Cowes
México D.F.
San Francisco
Bergamo
None
Lander
Eugene
Albuquerque
Lisboa
Barquisimeto
Torino
Charleroi
Rio de Janeiro
Köln
Cunewalde
Stuttgart
Buenos Aires
Münster
Portland
Kobenhavn
None
Luleå
Lisboa
Reggio Emilia
Kobenhavn
Versailles
Caracas
Warszawa
Madrid
Torino
London
Albuquerque
London
Bräcke
San Cristóbal
Buenos Aires
Lisboa
Madrid
Barcelona
Boise
Paris
Cowes
Köln
Berlin
Montréal
Resende
Butte
Buenos Aires
Portland
Lander
Butte
Nantes
Boise
Madrid
Albuquerque
Oulu
Lander
Portland
Warszawa
London
Helsinki
Rio de Janeiro
Madrid
Resende
Elgin
Caracas
Bräcke
Sao Paulo
Sevilla
Bergamo
Madrid
Helsinki
Cowes
London
Buenos Aires
Lille
Brandenburg
Salzburg
Lisboa
Madrid
Campinas
Berlin
Genève
Berlin
Brandenburg
Brandenburg
I. de Margarita
Montréal
Lisboa
None
Madrid
London
Paris
Madrid
München
Bräcke
Madrid
Reggio Emilia
Reggio Emilia
Paris
Rio de Janeiro
Madrid
Buenos Aires
Leipzig
Genève
Mannheim
Salzburg
Rio de Janeiro
Barcelona
Barquisimeto
London
México D.F.
Köln
Brandenburg
London
Kirkland
Butte
Genève
Barquisimeto
Buenos Aires
München
Montréal
Montréal
Nantes
Aachen
Sao Paulo
México D.F.
Sao Paulo
Genève
Stavern
Walla Walla
Stuttgart
Nantes
Graz
Rio de Janeiro
Nantes
Frankfurt a.M.
Mannheim
Montréal
Seattle
Cowes
Kirkland
Helsinki
Lille
Münster
Sao Paulo
Warszawa
London
Sao Paulo
London
Portland
Rio de Janeiro
Warszawa
Sevilla
Walla Walla
San Francisco
Sao Paulo
Cunewalde
Cork
Bern
Elgin
London
Stuttgart
Vancouver
Tsawassen
London
México D.F.
Madrid
None
Nantes
London
Bräcke
Rio de Janeiro
Nantes
Cowes
Elgin
Cork
Lander
Elgin
Toulouse
Madrid
México D.F.
Madrid
Lander
Sao Paulo
Aachen
Butte
Caracas
Bruxelles
Cowes
London
London
Sao Paulo
Toulouse
Lisboa
Barcelona
London
Cowes
Kirkland
San Francisco
Sao Paulo
Madrid
Paris
Brandenburg
Boise
Helsinki
Cork
México D.F.
Lisboa
Rio de Janeiro
Versailles
Graz
Cork
Lisboa
Köln
Anchorage
Walla Walla
Stuttgart
Marseille
Caracas
Bruxelles
Lander
I. de Margarita
Caracas
Sao Paulo
Buenos Aires
Portland
Lisboa
Buenos Aires
Cunewalde
Münster
London
Stuttgart
Salzburg
Tsawassen
Mannheim
I. de Margarita
Bräcke
Caracas
Warszawa
Cork
Genève
Leipzig
Paris
None
Sao Paulo
Graz
Oulu
Sao Paulo
Reggio Emilia
Warszawa
Kirkland
Stuttgart
Boise
Tsawassen
Lille
Stavern
Walla Walla
Sao Paulo
I. de Margarita
Tsawassen
Campinas
Buenos Aires
London
Barquisimeto
Montréal
México D.F.
Barcelona
Sao Paulo
Warszawa
Leipzig
Reims
Walla Walla
Sao Paulo
Versailles
San Francisco
Campinas
México D.F.
Toulouse
Lander
Lander
None
Nantes
London
Rio de Janeiro
Madrid
Walla Walla
Vancouver
Paris
Köln
I. de Margarita
Genève
Buenos Aires
Buenos Aires
Lille
Salzburg
Lander
Resende
Bräcke
Graz
Albuquerque
Charleroi
Eugene
Albuquerque
Buenos Aires
Münster
Portland
London
Sao Paulo
Sao Paulo
México D.F.
Graz
Warszawa
Toulouse
Barcelona
Lisboa
Rio de Janeiro
Warszawa
Frankfurt a.M.
Anchorage
None
San Francisco
Anchorage
Århus
Campinas
Kirkland
Caracas
Barcelona
Stavern
Mannheim
München
Bräcke
Aachen
México D.F.
Stavern
Aachen
Strasbourg
München
Sao Paulo
London
Warszawa
Sao Paulo
Portland
Nantes
London
Bergamo
Salzburg
Mannheim
Münster
Bräcke
Elgin
London
Lille
None
Boise
Torino
Nantes
Cowes
Campinas
Rio de Janeiro
Köln
Toulouse
Lander
Buenos Aires
None
Montréal
Sao Paulo
Marseille
Paris
Bern
London
Köln
Anchorage
México D.F.
Vancouver
Helsinki
Frankfurt a.M.
México D.F.
Portland
México D.F.
San Cristóbal
Helsinki
Rio de Janeiro
Montréal
Oulu
Cowes
Strasbourg
Tsawassen
Charleroi
Nantes
Tsawassen
México D.F.
I. de Margarita
Helsinki
Leipzig
London
Elgin
Graz
Buenos Aires
Warszawa
Paris
Sevilla
Kobenhavn
Lander
Bruxelles
Anchorage
Boise
Albuquerque
None
Bergamo
Anchorage
Buenos Aires
Sao Paulo
London
Cunewalde
Torino
Rio de Janeiro
Buenos Aires
Toulouse
Bräcke
Reggio Emilia
Reggio Emilia
None
Madrid
Sao Paulo
Luleå
None
Lyon
Lisboa
México D.F.
London
London
Resende
Buenos Aires
Butte
Kobenhavn
Albuquerque
Barquisimeto
Paris
Buenos Aires
Sevilla
Vancouver
None
Bruxelles
México D.F.
Rio de Janeiro
Montréal
Lyon
San Cristóbal
Albuquerque
Nantes
Bergamo
México D.F.
Butte
None
México D.F.
Oulu
Aachen
Lander
Sao Paulo
Buenos Aires
Oulu
Münster
Bern
Walla Walla
Cowes
Warszawa
Lisboa
Luleå
Boise
Eugene
Madrid
Buenos Aires
Tsawassen
Toulouse
Bruxelles
Köln
Stuttgart
Charleroi
Nantes
Buenos Aires
Cunewalde
Rio de Janeiro
San Cristóbal
San Cristóbal
Toulouse
Tsawassen
Münster
Marseille
London
Lisboa
London
Sao Paulo
Cunewalde
San Cristóbal
México D.F.
México D.F.
Bräcke
Leipzig
Charleroi
Warszawa
Butte
Oulu
Salzburg
San Cristóbal
Kirkland
Cunewalde
Montréal
Nantes
Brandenburg
Caracas
Montréal
Rio de Janeiro
Lisboa
Seattle
Bruxelles
London
Versailles
Charleroi
Lille
Montréal
Bergamo
Vancouver
Reggio Emilia
Eugene
Strasbourg
Madrid
London
Sao Paulo
Rio de Janeiro
Resende
Versailles
Elgin
Cowes
Graz
Warszawa
Helsinki
Seattle
Kirkland
Anchorage
Sao Paulo
Charleroi
Torino
Butte
London
Salzburg
London
Köln
Vancouver
I. de Margarita
Cowes
London
Campinas
Charleroi
Leipzig
Anchorage
México D.F.
Helsinki
Helsinki
None
Berlin
Bergamo
Brandenburg
Rio de Janeiro
Helsinki
Madrid
Århus
Cunewalde
Luleå
Portland
Tsawassen
Montréal
Eugene
Luleå
Sao Paulo
Torino
Stuttgart
Portland
Reims
Stavern
Vancouver
Bern
None
Warszawa
Lyon
London
San Cristóbal
I. de Margarita
Kobenhavn
Kirkland
Luleå
México D.F.
London
Nantes
Warszawa
Paris
Versailles
Albuquerque
Berlin
Warszawa
Torino
Reggio Emilia
San Francisco
Madrid
Rio de Janeiro
Buenos Aires
Bräcke
Rio de Janeiro
Buenos Aires
Portland
Kobenhavn
Vancouver
Bern
Elgin
Lisboa
Münster
Caracas
London
Graz
Århus
Salzburg
Lyon
Salzburg
Lander
Rio de Janeiro
London
Stuttgart
México D.F.
México D.F.
Vancouver
Stavern
London
Eugene
London
Reggio Emilia
Walla Walla
Reims
Charleroi
Stavern
Sao Paulo
Buenos Aires
Brandenburg
Portland
Münster
Marseille
Bern
Boise
Sao Paulo
México D.F.
Sao Paulo
Sao Paulo
México D.F.
México D.F.
Resende
México D.F.
Århus
Rio de Janeiro
Versailles
Campinas
Stuttgart
Rio de Janeiro
Strasbourg
Albuquerque
Köln
Paris
London
Lisboa
London
Reims
Bruxelles
Münster
None
Berlin
Marseille
Bruxelles
Kirkland
Paris
Cork
Lisboa
México D.F.
Stavern
Butte
Kobenhavn
Sao Paulo
Portland
Buenos Aires
Sao Paulo
Rio de Janeiro
Aachen
Mannheim
Cowes
Oulu
México D.F.
Toulouse
Bergamo
Stuttgart
Sao Paulo
London
Bern
Rio de Janeiro
Caracas
Strasbourg
Bräcke
Madrid
México D.F.
Brandenburg
Anchorage
Lyon
Lander
Sao Paulo
Eugene
Rio de Janeiro
Köln
London
Buenos Aires
Resende
Caracas
London
Nantes
Lander
Mannheim
Charleroi
None
Bräcke
Tsawassen
London
Aachen
Nantes
Oulu
Charleroi
Madrid
Aachen
Albuquerque
Buenos Aires
Campinas
Lisboa
Boise
Sao Paulo
London
Helsinki
Cowes
Sevilla
Kirkland
Brandenburg
Barquisimeto
México D.F.
México D.F.
Resende
Sao Paulo
San Francisco
Lyon
Lisboa
Münster
Resende
Oulu
Toulouse
Helsinki
México D.F.
Rio de Janeiro
México D.F.
Buenos Aires
I. de Margarita
Boise
Caracas
Münster
Butte
Madrid
Århus
Mannheim
Frankfurt a.M.
London
México D.F.
Torino
México D.F.
Reims
Buenos Aires
Bergamo
Sao Paulo
México D.F.
None
Barcelona
México D.F.
Sao Paulo
Stavern
Buenos Aires
Madrid
Lille
Barcelona
Charleroi
Oulu
München
Rio de Janeiro
Rio de Janeiro
Albuquerque
Kirkland
Bern
Lyon
Buenos Aires
Kobenhavn
Sao Paulo
Madrid
Genève
Reggio Emilia
Campinas
Walla Walla
Charleroi
Reggio Emilia
Berlin
Tsawassen
Sevilla
Warszawa
Lander
Charleroi
Warszawa
Stavern
México D.F.
Madrid
London
Lisboa
Charleroi
México D.F.
Buenos Aires
Nantes
Kirkland
Walla Walla
México D.F.
Sao Paulo
Butte
Barcelona
Sevilla
Nantes
Portland
München
Münster
London
México D.F.
Sao Paulo
Luleå
Toulouse
Marseille
Torino
Butte
London
Leipzig
Salzburg
Lisboa
México D.F.
None
Caracas
Graz
Buenos Aires
Rio de Janeiro
Nantes
Walla Walla
Campinas
Lyon
Köln
London
Buenos Aires
Sao Paulo
Brandenburg
Buenos Aires
Toulouse
Sevilla
Barcelona
Madrid
Vancouver
México D.F.
Münster
Lisboa
Sao Paulo
None
Helsinki
Köln
None
Sao Paulo
Versailles
México D.F.
Marseille
Cowes
None
Versailles
Genève
Bräcke
Charleroi
México D.F.
Tsawassen
Nantes
Paris
Mannheim
México D.F.
Boise
Madrid
Rio de Janeiro
Bern
Buenos Aires
Buenos Aires
Cowes
Sevilla
Strasbourg
Frankfurt a.M.
Madrid
Kirkland
Bergamo
Mannheim
Kobenhavn
I. de Margarita
Campinas
Madrid
Rio de Janeiro
México D.F.
Salzburg
Kirkland
México D.F.
Sao Paulo
Charleroi
Versailles
Brandenburg
Madrid
Lille
Sao Paulo
Eugene
Kobenhavn
Lisboa
México D.F.
Barquisimeto
Tsawassen
Strasbourg
Münster
Cowes
Anchorage
London
Barcelona
México D.F.
Mannheim
Torino
Lille
Anchorage
México D.F.
Boise
México D.F.
Rio de Janeiro
Versailles
Rio de Janeiro
Buenos Aires
Elgin
México D.F.
Marseille
Bruxelles
Versailles
None
London
Torino
San Cristóbal
Paris
Lisboa
Madrid
Portland
None
Nantes
Graz
México D.F.
México D.F.
Frankfurt a.M.
Bern
México D.F.
Rio de Janeiro
Campinas
None
Berlin
Rio de Janeiro
Paris
México D.F.
Vancouver
Oulu
Stavern
Bruxelles
Salzburg
London
Walla Walla
Helsinki
London
Kobenhavn
Campinas
London
Resende
Butte
Cowes
Lyon
Lander
Bräcke
Vancouver
Tsawassen
Resende
I. de Margarita
México D.F.
Rio de Janeiro
Bräcke
Kirkland
Portland
Bräcke
Köln
Reggio Emilia
Anchorage
Portland
Buenos Aires
Reims
San Francisco
México D.F.
Resende
Paris
Versailles
Seattle
Oulu
Lander
Vancouver
Helsinki
Nantes
Lander
Barquisimeto
Caracas
Münster
Luleå
Münster
Elgin
Lisboa
Buenos Aires
Kirkland
Buenos Aires
Kirkland
Caracas
Luleå
Oulu
Buenos Aires
México D.F.
Berlin
Resende
Münster
Rio de Janeiro
Charleroi
Århus
Lisboa
Barquisimeto
Sao Paulo
Montréal
Caracas
Århus
Kobenhavn
Stavern
Versailles
Stuttgart
Kirkland
München

,Region,dinero_generado,OrderDate,City,Date,year,month,day,latitud,longuitud
0,North America,28992.85,2012-07-10 15:40:46,Eugene,2012-07,2012,7,10,44.050505,-123.095051
1,South America,24589.35,2012-07-10 20:28:57,Rio de Janeiro,2012-07,2012,7,10,-22.911014,-43.209373
2,North America,52573.43,2012-07-11 01:09:16,Portland,2012-07,2012,7,11,45.520247,-122.674194
3,Northern Europe,23413.40,2012-07-11 20:26:28,Bräcke,2012-07,2012,7,11,62.783333,15.666667
4,British Isles,30387.75,2012-07-11 21:17:36,London,2012-07,2012,7,11,51.489334,-0.144055
...,...,...,...,...,...,...,...,...,...,...
15927,North America,34282.53,2023-10-25 13:00:29,Seattle,2023-10,2023,10,25,47.603832,-122.330062
15928,Southern Europe,60918.66,2023-10-26 06:28:53,Madrid,2023-10,2023,10,26,40.416705,-3.703582
15929,Western Europe,51375.33,2023-10-27 06:38:44,Leipzig,2023-10,2023,10,27,51.340632,12.374733
15930,Southern Europe,27159.69,2023-10-27 18:17:38,Madrid,2023-10,2023,10,27,40.416705,-3.703582
15931,Western Europe,10959.04,2023-10-28 00:09:48,Bruxelles,2023-10,2023,10,28,50.846557,4.351697

In [408]:
d

,Region,dinero_generado,OrderDate,City,Date,year,month,day,latitud,longuitud
0,North America,28992.85,2012-07-10 15:40:46,Eugene,2012-07,2012,7,10,44.050505,-123.095051
1,South America,24589.35,2012-07-10 20:28:57,Rio de Janeiro,2012-07,2012,7,10,-22.911014,-43.209373
2,North America,52573.43,2012-07-11 01:09:16,Portland,2012-07,2012,7,11,45.520247,-122.674194
3,Northern Europe,23413.40,2012-07-11 20:26:28,Bräcke,2012-07,2012,7,11,62.783333,15.666667
4,British Isles,30387.75,2012-07-11 21:17:36,London,2012-07,2012,7,11,51.489334,-0.144055
...,...,...,...,...,...,...,...,...,...,...
15927,North America,34282.53,2023-10-25 13:00:29,Seattle,2023-10,2023,10,25,47.603832,-122.330062
15928,Southern Europe,60918.66,2023-10-26 06:28:53,Madrid,2023-10,2023,10,26,40.416705,-3.703582
15929,Western Europe,51375.33,2023-10-27 06:38:44,Leipzig,2023-10,2023,10,27,51.340632,12.374733
15930,Southern Europe,27159.69,2023-10-27 18:17:38,Madrid,2023-10,2023,10,27,40.416705,-3.703582
15931,Western Europe,10959.04,2023-10-28 00:09:48,Bruxelles,2023-10,2023,10,28,50.846557,4.351697

In [409]:
df1_2=pd.DataFrame(d)

In [410]:
df1_2=df1_2
df1_2 = df1_2.dropna(axis=0, subset=['latitud','longuitud', 'dinero_generado', "Date"])
df1_2


time_index1 = list(df1_2['Date'].sort_values().astype('str').unique())
time_index1

['2012-07',
 '2012-08',
 '2012-09',
 '2012-10',
 '2012-11',
 '2012-12',
 '2013-01',
 '2013-02',
 '2013-03',
 '2013-04',
 '2013-05',
 '2013-06',
 '2013-07',
 '2013-08',
 '2013-09',
 '2013-10',
 '2013-11',
 '2013-12',
 '2014-01',
 '2014-02',
 '2014-03',
 '2014-04',
 '2014-05',
 '2014-06',
 '2014-07',
 '2014-08',
 '2014-09',
 '2014-10',
 '2014-11',
 '2014-12',
 '2015-01',
 '2015-02',
 '2015-03',
 '2015-04',
 '2015-05',
 '2015-06',
 '2015-07',
 '2015-08',
 '2015-09',
 '2015-10',
 '2015-11',
 '2015-12',
 '2016-01',
 '2016-02',
 '2016-03',
 '2016-04',
 '2016-05',
 '2016-06',
 '2016-07',
 '2016-08',
 '2016-09',
 '2016-10',
 '2016-11',
 '2016-12',
 '2017-01',
 '2017-02',
 '2017-03',
 '2017-04',
 '2017-05',
 '2017-06',
 '2017-07',
 '2017-08',
 '2017-09',
 '2017-10',
 '2017-11',
 '2017-12',
 '2018-01',
 '2018-02',
 '2018-03',
 '2018-04',
 '2018-05',
 '2018-06',
 '2018-07',
 '2018-08',
 '2018-09',
 '2018-10',
 '2018-11',
 '2018-12',
 '2019-01',
 '2019-02',
 '2019-03',
 '2019-04',
 '2019-05',
 '2019-06',
 '2019-07',
 '2019-08',
 '2019-09',
 '2019-10',
 '2019-11',
 '2019-12',
 '2020-01',
 '2020-02',
 '2020-03',
 '2020-04',
 '2020-05',
 '2020-06',
 '2020-07',
 '2020-08',
 '2020-09',
 '2020-10',
 '2020-11',
 '2020-12',
 '2021-01',
 '2021-02',
 '2021-03',
 '2021-04',
 '2021-05',
 '2021-06',
 '2021-07',
 '2021-08',
 '2021-09',
 '2021-10',
 '2021-11',
 '2021-12',
 '2022-01',
 '2022-02',
 '2022-03',
 '2022-04',
 '2022-05',
 '2022-06',
 '2022-07',
 '2022-08',
 '2022-09',
 '2022-10',
 '2022-11',
 '2022-12',
 '2023-01',
 '2023-02',
 '2023-03',
 '2023-04',
 '2023-05',
 '2023-06',
 '2023-07',
 '2023-08',
 '2023-09',
 '2023-10']

In [411]:
import folium # pip install folium
from folium import plugins
# import ipywidgets # pip install ipywidgets
import geocoder # pip install geocoder
# import geopy # pip install geopy
import numpy as np
import pandas as pd
from vega_datasets import data as vds # pip install vega_datasets
from folium.plugins import HeatMapWithTime

In [412]:
df1_2['Date'] = df1_2['Date'].sort_values(ascending=True)
data1 = []
for _, p in df1_2.groupby('Date'):
    data1.append([[row['latitud'], row['longuitud'], row['dinero_generado']] for _, row in p.iterrows()])
data1

[[[44.0505054, -123.0950506, 28992.85],
  [-22.9110137, -43.2093727, 24589.35],
  [45.5202471, -122.674194, 52573.43],
  [62.783333, 15.666667, 23413.4],
  [51.4893335, -0.1440551, 30387.75],
  [51.4893335, -0.1440551, 11022.53],
  [35.0841034, -106.650985, 20809.41],
  [51.8985136, -8.4726423, 5012.36],
  [-34.6083696, -58.4440583, 47249.88],
  [55.6867243, 12.5700724, 42942.83],
  [45.0677551, 7.6824892, 32054.53],
  [43.2961743, 5.3699525, 18847.2],
  [51.098481, 14.514475, 22944.85],
  [44.6086674, 10.5940667, 56428.34],
  [19.3207722, -99.1514678, 10615.4],
  [40.4167047, -3.7035825, 10946.3],
  [51.3406321, 12.3747329, 47755.26],
  [43.2961743, 5.3699525, 25685.16],
  [-23.5506507, -46.6333824, 4499.68],
  [45.5202471, -122.674194, 9983.7],
  [-22.9110137, -43.2093727, 21857.43],
  [50.6365654, 3.0635282, 61758.78],
  [19.3207722, -99.1514678, 2164.25],
  [43.6166163, -116.200886, 50313.94],
  [11.0205596, -63.9073984, 25291.2],
  [-23.5506507, -46.6333824, 48415.33],
  [41.3825802, 2.177073, 52956.49],
  [51.4893335, -0.1440551, 12950.4],
  [50.776351, 6.083862, 53885.01],
  [44.6086674, 10.5940667, 24575.9],
  [19.3207722, -99.1514678, 17904.920000000002],
  [39.9059878, -116.9843374, 10326.2],
  [45.7578137, 4.8320114, 57753.99],
  [45.7578137, 4.8320114, 53158.61],
  [52.2337172, 21.0714322, 31950.8],
  [51.098481, 14.514475, 6610.3],
  [45.7578137, 4.8320114, 1975.0],
  [34.0, -40.0, 26418.920000000002],
  [50.4116233, 4.444528, 15827.37],
  [37.7792588, -122.4193286, 40970.45],
  [10.5060934, -66.9146008, 55952.14],
  [51.4893335, -0.1440551, 47715.77],
  [34.0, -40.0, 44520.4],
  [56.1496278, 10.2134046, 6383.1],
  [40.4167047, -3.7035825, 16545.85],
  [19.3207722, -99.1514678, 36246.81],
  [47.2186371, -1.5541362, 53012.7],
  [19.3207722, -99.1514678, 50595.85],
  [45.7578137, 4.8320114, 45698.67],
  [-23.5506507, -46.6333824, 32464.25],
  [50.776351, 6.083862, 18591.01],
  [44.6086674, 10.5940667, 19817.08],
  [38.7077507, -9.1365919, 41230.31],
  [44.6086674, 10.5940667, 3375.25],
  [34.0, -40.0, 4982.5],
  [-23.5506507, -46.6333824, 4336.93],
  [-34.6083696, -58.4440583, 35605.71],
  [50.938361, 6.959974, 13073.52],
  [-34.6083696, -58.4440583, 36861.63],
  [51.4893335, -0.1440551, 323.0],
  [17.3156929, -62.7446806, 40632.41],
  [42.03726, -88.2810994, 30693.71],
  [46.9484742, 7.4521749, 60918.92],
  [41.3825802, 2.177073, 9194.39],
  [-22.9110137, -43.2093727, 42917.67],
  [51.3406321, 12.3747329, 34039.54],
  [-23.5506507, -46.6333824, 55931.37],
  [48.8588897, 2.320041, 60217.38],
  [10.0774374, -69.3222293, 20522.03]],
 [[46.9484742, 7.4521749, 47346.47],
  [51.4893335, -0.1440551, 41790.72],
  [47.2186371, -1.5541362, 23259.18],
  [37.3886303, -5.9953403, 51622.48],
  [19.3207722, -99.1514678, 14855.85],
  [65.0117869, 25.4701983, 34521.44],
  [41.3825802, 2.177073, 782.2],
  [-34.6083696, -58.4440583, 4340.7],
  [52.8455492, 13.2461296, 8954.97],
  [39.9059878, -116.9843374, 33873.79],
  [34.0, -40.0, 4085.0],
  [10.5060934, -66.9146008, 12223.3],
  [49.2608724, -123.113952, 10630.1],
  [46.9484742, 7.4521749, 47434.17],
  [51.3406321, 12.3747329, 18817.85],
  [50.776351, 6.083862, 40335.79],
  [48.1371079, 11.5753822, 41052.38],
  [49.2608724, -123.113952, 21077.85],
  [39.6519275, -121.5858444, 8652.17],
  [50.8465573, 4.351697, 20159.87],
  [34.0, -40.0, 9863.72],
  [47.6765382, -122.2070775, 45635.88],
  [51.4893335, -0.1440551, 42830.63],
  [65.5831187, 22.1459535, 44624.54],
  [-34.6083696, -58.4440583, 30511.71],
  [-23.5506507, -46.6333824, 1256.5],
  [49.2608724, -123.113952, 56017.92],
  [48.8588897, 2.320041, 2081.0],
  [17.3156929, -62.7446806, 55867.55],
  [40.4167047, -3.7035825, 18296.18],
  [40.4167047, -3.7035825, 30849.1],
  [42.03726, -88.2810994, 12362.9],
  [52.797273, 7.4345519, 35855.08],
  [10.5060934, -66.9146008, 1003.2],
  [46.2017559, 6.1466014, 21088.36],
  [51.4893335, -0.1440551, 16597.2],
  [11.0205596, -63.9073984, 23895.2],
  [51.4893335, -0.1440551, 30849.48],
  [11.0205596, -63.9073984, 57948.45],
  [47.2186371, -1.5541362, 55617.75],
  [43.6166163, -116.200886, 19319.29],
  [-22.9110137, -43.2093727, 37439.2],
  [48.1371079, 11.5753822, 3079.95],
  [40.4167047, -3.7035825, 42540.44],
  [10.0774374, -69.3222293, 28068.3],
  [47.2186371, -1.5541362, 33974.57],
  [17.3156929, -62.7446806, 21860.56],
  [51.3406321, 12.3747329, 28955.8],
  [47.0708678, 15.4382786, 59116.51],
  [48.584614, 7.7507127, 36995.92],
  [37.3886303, -5.9953403, 15725.2],
  [48.1371079, 11.5753822, 26562.49],
  [40.4167047, -3.7035825, 38874.76],
  [51.4893335, -0.1440551, 47007.74],
  [19.3207722, -99.1514678, 24192.61],
  [37.7792588, -122.4193286, 23412.1],
  [65.5831187, 22.1459535, 393.0],
  [49.2577886, 4.031926, 31406.47],
  [62.783333, 15.666667, 10995.82],
  [52.2337172, 21.0714322, 24103.9],
  [50.6365654, 3.0635282, 47169.95],
  [40.4167047, -3.7035825, 23834.35],
  [43.6044622, 1.4442469, 11547.7],
  [44.6086674, 10.5940667, 33981.340000000004],
  [62.783333, 15.666667, 25799.52],
  [55.6867243, 12.5700724, 12062.95],
  [47.2186371, -1.5541362, 62992.83],
  [34.0, -40.0, 53617.56],
  [51.4893335, -0.1440551, 46893.3],
  [48.8588897, 2.320041, 255.0],
  [43.6044622, 1.4442469, 54969.56],
  [19.3207722, -99.1514678, 43844.34],
  [44.6086674, 10.5940667, 22757.3],
  [-34.6083696, -58.4440583, 52464.63],
  [51.3406321, 12.3747329, 44901.03],
  [48.8035403, 2.1266886, 20687.05],
  [-23.5506507, -46.6333824, 44676.76],
  [-22.9110137, -43.2093727, 21764.45],
  [49.2577886, 4.031926, 48944.9],
  [52.510885, 13.3989367, 6959.05],
  [34.0, -40.0, 3112.25],
  [43.6166163, -116.200886, 57688.09],
  [48.7784485, 9.1800132, 62701.37],
  [47.6038321, -122.330062, 30392.0],
  [43.2961743, 5.3699525, 34641.04],
  [40.4167047, -3.7035825, 12525.1],
  [51.8985136, -8.4726423, 50829.09],
  [52.8455492, 13.2461296, 6633.9],
  [52.2337172, 21.0714322, 13770.15],
  [11.0205596, -63.9073984, 54467.57],
  [44.6086674, 10.5940667, 2779.3],
  [50.8465573, 4.351697, 1110.0],
  [-22.9110137, -43.2093727, 12567.8],
  [50.8465573, 4.351697, 18357.239999999998],
  [50.8465573, 4.351697, 30662.25],
  [45.7578137, 4.8320114, 19649.17],
  [55.6867243, 12.5700724, 63519.88],
  [40.4167047, -3.7035825, 19101.24],
  [39.9059878, -116.9843374, 36020.01],
  [50.938361, 6.959974, 24775.52],
  [-22.9110137, -43.2093727, 31626.56],
  [50.6365654, 3.0635282, 4846.5],
  [47.7981346, 13.0464806, 18061.75],
  [17.3156929, -62.7446806, 150.0],
  [43.2961743, 5.3699525, 55015.79],
  [51.4893335, -0.1440551, 30254.37],
  [-23.5506507, -46.6333824, 2489.1],
  [-23.5506507, -46.6333824, 20900.17],
  [65.5831187, 22.1459535, 52487.78],
  [50.6365654, 3.0635282, 38204.09],
  [50.6365654, 3.0635282, 57685.13],
  [34.0, -40.0, 156.0],
  [44.6086674, 10.5940667, 8867.0],
  [55.6867243, 12.5700724, 47200.79],
  [19.3207722, -99.1514678, 8243.4],
  [41.3825802, 2.177073, 41116.56],
  [17.3156929, -62.7446806, 53951.17],
  [51.4893335, -0.1440551, 50785.31],
  [47.6038321, -122.330062, 22679.12],
  [52.510885, 13.3989367, 19811.5],
  [37.7792588, -122.4193286, 62322.32]],
 [[48.8035403, 2.1266886, 7372.66],
  [44.0505054, -123.0950506, 35760.83],
  [46.2017559, 6.1466014, 37506.49],
  [51.4893335, -0.1440551, 30759.75],
  [48.8588897, 2.320041, 11448.19],
  [-34.6083696, -58.4440583, 7176.1],
  [19.3207722, -99.1514678, 17548.6],
  [10.0774374, -69.3222293, 6000.7],
  [43.2961743, 5.3699525, 26412.87],
  [48.8588897, 2.320041, 15112.3],
  [40.4167047, -3.7035825, 7623.030000000001],
  [47.2186371, -1.5541362, 22215.26],
  [52.8455492, 13.2461296, 8023.55],
  [52.797273, 7.4345519, 48537.0],
  [34.0, -40.0, 24309.06],
  [40.4167047, -3.7035825, 28349.69],
  [43.6166163, -116.200886, 50886.89],
  [49.2577886, 4.031926, 21437.66],
  [46.2055155, -118.5174284, 43297.15],
  [43.6044622, 1.4442469, 16157.54],
  [-23.5506507, -46.6333824, 9550.93],
  [38.7077507, -9.1365919, 8684.55],
  [48.8588897, 2.320041, 57412.51],
  [-23.5506507, -46.6333824, 55868.45],
  [39.6519275, -121.5858444, 30730.75],
  [48.8588897, 2.320041, 48641.0],
  [52.510885, 13.3989367, 37222.19],
  [34.0, -40.0, 21144.52],
  [19.3207722, -99.1514678, 33455.84],
  [19.3207722, -99.1514678, 29314.92],
  [51.098481, 14.514475, 50369.95],
  [60.1674881, 24.9427473, 1920.1],
  [50.7633176, -1.2985186, 29175.29],
  [50.4116233, 4.444528, 25534.0],
  [47.6765382, -122.2070775, 18370.05],
  [45.5202471, -122.674194, 24821.79],
  [48.584614, 7.7507127, 55259.77],
  [-23.5506507, -46.6333824, 49584.06],
  [-22.9056391, -47.059564, 7631.95],
  [45.5031824, -73.5698065, 42762.16],
  [50.7633176, -1.2985186, 12043.2],
  [-23.5506507, -46.6333824, 30676.99],
  [-23.5506507, -46.6333824, 1368.0],
  [19.3207722, -99.1514678, 10788.0],
  [40.4167047, -3.7035825, 9798.25],
  [10.0774374, -69.3222293, 56795.18],
  [44.6086674, 10.5940667, 4201.06],
  [43.2961743, 5.3699525, 31775.36],
  [45.5202471, -122.674194, 47742.94],
  [37.3886303, -5.9953403, 59742.34],
  [37.3886303, -5.9953403, 3452.7],
  [11.0205596, -63.9073984, 32373.42],
  [38.7077507, -9.1365919, 1038.21],
  [38.7077507, -9.1365919, 50894.7],
  [47.2186371, -1.5541362, 1590.0],
  [17.3156929, -62.7446806, 8752.75],
  [48.1371079, 11.5753822, 57053.83],
  [37.3886303, -5.9953403, 52092.87],
  [51.9625101, 7.6251879, 27197.74],
  [50.6365654, 3.0635282, 13678.699999999999],
  [55.6867243, 12.5700724, 9879.710000000001],
  [47.2186371, -1.5541362, 47502.21],
  [51.8985136, -8.4726423, 16757.35],
  [62.783333, 15.666667, 41430.02],
  [10.5060934, -66.9146008, 31034.52],
  [50.7633176, -1.2985186, 4879.6],
  [52.797273, 7.4345519, 8558.68],
  [48.8588897, 2.320041, 43819.1],
  [46.9484742, 7.4521749, 24929.78],
  [52.797273, 7.4345519, 14518.85],
  [50.4116233, 4.444528, 50751.69],
  [-23.5506507, -46.6333824, 32289.82],
  [10.5060934, -66.9146008, 20823.67],
  [49.2608724, -123.113952, 55211.83],
  [50.8465573, 4.351697, 23661.55],
  [-22.4683626, -44.4463494, 18641.1],
  [50.8465573, 4.351697, 23675.25],
  [45.5202471, -122.674194, 3979.0],
  [37.3886303, -5.9953403, 36080.91],
  [51.8985136, -8.4726423, 42098.01],
  [46.2017559, 6.1466014, 39899.2],
  [47.0708678, 15.4382786, 35929.01],
  [42.03726, -88.2810994, 44019.14],
  [51.4893335, -0.1440551, 14323.45],
  [48.8588897, 2.320041, 37838.57],
  [47.6038321, -122.330062, 35468.35],
  [48.8588897, 2.320041, 20180.98],
  [46.2055155, -118.5174284, 49572.59],
  [40.4167047, -3.7035825, 42895.340000000004],
  [19.3207722, -99.1514678, 33400.31],
  [-23.5506507, -46.6333824, 23179.72],
  [65.0117869, 25.4701983, 50500.94],
  [-23.5506507, -46.6333824, 23406.48],
  [52.797273, 7.4345519, 30981.989999999998],
  [45.5031824, -73.5698065, 6985.5],
  [10.0774374, -69.3222293, 42667.57],
  [45.7566557, 9.7542192, 38434.15],
  [49.2608724, -123.113952, 11263.34],
  [40.4167047, -3.7035825, 3891.55],
  [45.0677551, 7.6824892, 23469.42],
  [-22.9110137, -43.2093727, 22908.0],
  [65.0117869, 25.4701983, 18336.85],
  [34.0, -40.0, 36188.8],
  [-23.5506507, -46.6333824, 22879.07],
  [61.2163129, -149.894852, 20768.6],
  [-34.6083696, -58.4440583, 28436.65],
  [-23.5506507, -46.6333824, 29809.34],
  [48.8588897, 2.320041, 56669.44],
  [51.4893335, -0.1440551, 25359.67],
  [-22.9056391, -47.059564, 50763.909999999996],
  [65.5831187, 22.1459535, 47238.17],
  [19.3207722, -99.1514678, 10207.7],
  [56.1496278, 10.2134046, 48580.96],
  [51.4893335, -0.1440551, 48513.35],
  [19.3207722, -99.1514678, 65568.04],
  [19.3207722, -99.1514678, 7549.9],
  [51.3406321, 12.3747329, 43613.159999999996],
  [48.584614, 7.7507127, 47739.48]],
 [[49.2608724, -123.113952, 23907.6],
  [55.6867243, 12.5700724, 16850.75],
  [48.8035403, 2.1266886, 49952.5],
  [-23.5506507, -46.6333824, 33787.51],
  [44.0505054, -123.0950506, 29450.149999999998],
  [48.584614, 7.7507127, 30470.2],
  [51.098481, 14.514475, 9639.38],
  [50.8465573, 4.351697, 25368.75],
  [-22.9110137, -43.2093727, 2507.0],
  [45.7578137, 4.8320114, 22002.6],
  [51.4893335, -0.1440551, 29087.44],
  [51.4893335, -0.1440551, 44824.29],
  [48.8588897, 2.320041, 50599.17],
  [51.098481, 14.514475, 7247.65],
  [-23.5506507, -46.6333824, 10072.4],
  [40.4167047, -3.7035825, 33215.48],
  [45.7566557, 9.7542192, 24830.73],
  [48.1371079, 11.5753822, 7685.75],
  [43.6044622, 1.4442469, 36544.11],
  [52.510885, 13.3989367, 35474.2],
  [19.3207722, -99.1514678, 27982.81],
  [34.0, -40.0, 50664.62],
  [37.3886303, -5.9953403, 44828.55],
  [43.6166163, -116.200886, 42933.24],
  [51.4893335, -0.1440551, 31872.59],
  [51.8985136, -8.4726423, 24245.17],
  [50.1106444, 8.6820917, 23244.95],
  [51.9625101, 7.6251879, 28173.920000000002],
  [-22.4683626, -44.4463494, 58953.44],
  [38.7077507, -9.1365919, 20649.11],
  [50.6365654, 3.0635282, 45100.93],
  [48.7784485, 9.1800132, 47802.71],
  [39.6519275, -121.5858444, 40077.51],
  [46.9484742, 7.4521749, 13337.57],
  [-22.9110137, -43.2093727, 15341.1],
  [-22.9056391, -47.059564, 37306.36],
  [52.2337172, 21.0714322, 16321.71],
  [-23.5506507, -46.6333824, 23533.19],
  [51.4893335, -0.1440551, 10875.95],
  [35.0841034, -106.650985, 1755.6999999999998],
  [47.0708678, 15.4382786, 37988.19],
  [10.0774374, -69.3222293, 58563.92],
  [19.3207722, -99.1514678, 58253.18],
  [-22.9110137, -43.2093727, 36493.72],
  [51.4893335, -0.1440551, 41109.24],
  [62.783333, 15.666667, 54548.76],
  [-22.9110137, -43.2093727, 46699.32],
  [42.03726, -88.2810994, 4614.26],
  [34.0, -40.0, 47624.18],
  [-22.9056391, -47.059564, 39536.1],
  [35.0841034, -106.650985, 24087.28],
  [-23.5506507, -46.6333824, 24237.71],
  [44.6086674, 10.5940667, 48443.45],
  [37.3886303, -5.9953403, 2179.8999999999996],
  [-34.6083696, -58.4440583, 5608.75],
  [35.0841034, -106.650985, 33049.38],
  [51.4893335, -0.1440551, 27963.63],
  [48.584614, 7.7507127, 798.0],
  [50.7633176, -1.2985186, 7910.599999999999],
  [48.7784485, 9.1800132, 46029.69],
  [47.6765382, -122.2070775, 42585.22],
  [40.4167047, -3.7035825, 8298.2],
  [47.6765382, -122.2070775, 25581.76],
  [17.3156929, -62.7446806, 556.12],
  [-22.4683626, -44.4463494, 30523.98],
  [11.0205596, -63.9073984, 10374.36],
  [19.3207722, -99.1514678, 46651.63],
  [50.8465573, 4.351697, 36522.62],
  [43.6044622, 1.4442469, 18447.89],
  [-22.9110137, -43.2093727, 25734.35],
  [60.1674881, 24.9427473, 47746.6],
  [45.5202471, -122.674194, 41777.85],
  [39.9059878, -116.9843374, 22804.06],
  [51.4893335, -0.1440551, 1730.0],
  [51.3406321, 12.3747329, 30373.9],
  [51.8985136, -8.4726423, 20469.0],
  [-22.9110137, -43.2093727, 17712.4],
  [46.2017559, 6.1466014, 36259.97],
  [19.3207722, -99.1514678, 41024.15],
  [43.6044622, 1.4442469, 39874.88],
  [49.2608724, -123.113952, 312.0],
  [38.7077507, -9.1365919, 18903.53],
  [50.6365654, 3.0635282, 8049.55],
  [65.5831187, 22.1459535, 27417.16],
  [34.0, -40.0, 39463.96],
  [48.1371079, 11.5753822, 66072.06],
  [51.4893335, -0.1440551, 55994.22],
  [40.4167047, -3.7035825, 35306.41],
  [47.2186371, -1.5541362, 23671.2],
  [62.783333, 15.666667, 56473.85],
  [-22.9056391, -47.059564, 1393.95],
  [42.03726, -88.2810994, 16704.23],
  [60.1674881, 24.9427473, 20332.42],
  [51.4893335, -0.1440551, 5132.15],
  [50.1106444, 8.6820917, 10012.45],
  [51.4893335, -0.1440551, 40530.3],
  [39.6519275, -121.5858444, 60443.95],
  [45.0677551, 7.6824892, 15476.22],
  [-22.9110137, -43.2093727, 40087.09],
  [50.776351, 6.083862, 14397.53],
  [-22.9110137, -43.2093727, 30501.1],
  [-22.9110137, -43.2093727, 28343.3],
  [51.4893335, -0.1440551, 43343.76],
  [35.0841034, -106.650985, 43162.85],
  [39.6519275, -121.5858444, 23300.010000000002],
  [47.6765382, -122.2070775, 15242.25],
  [40.4167047, -3.7035825, 5143.5],
  [50.1106444, 8.6820917, 42116.47],
  [-22.4683626, -44.4463494, 43643.61],
  [38.7077507, -9.1365919, 23986.13],
  [-22.9110137, -43.2093727, 27265.76]],
 [[-22.9110137, -43.2093727, 23451.2],
  [51.4893335, -0.1440551, 55692.56],
  [49.4892913, 8.4673098, 13735.5],
  [56.1496278, 10.2134046, 12398.71],
  [43.2961743, 5.3699525, 55225.24],
  [-23.5506507, -46.6333824, 60963.1],
  [40.4167047, -3.7035825, 5740.24],
  [11.0205596, -63.9073984, 9476.85],
  [47.6038321, -122.330062, 23663.51],
  [17.3156929, -62.7446806, 14544.53],
  [50.1106444, 8.6820917, 43145.67],
  [46.2017559, 6.1466014, 45362.87],
  [37.3886303, -5.9953403, 41818.4],
  [35.0841034, -106.650985, 30646.93],
  [43.6166163, -116.200886, 20952.82],
  [46.9484742, 7.4521749, 14429.710000000001],
  [37.7792588, -122.4193286, 122.5],
  [51.3406321, 12.3747329, 36906.21],
  [51.4893335, -0.1440551, 47180.51],
  [51.3406321, 12.3747329, 28390.0],
  [-22.9110137, -43.2093727, 24905.1],
  [61.2163129, -149.894852, 54674.29],
  [48.1371079, 11.5753822, 15536.87],
  [65.5831187, 22.1459535, 29773.43],
  [45.7578137, 4.8320114, 11830.03],
  [51.098481, 14.514475, 3560.6],
  [45.5202471, -122.674194, 24795.95],
  [51.8985136, -8.4726423, 17398.95],
  [-34.6083696, -58.4440583, 63292.72],
  [48.8588897, 2.320041, 2647.35],
  [41.3825802, 2.177073, 14242.86],
  [51.4893335, -0.1440551, 10340.630000000001],
  [45.7566557, 9.7542192, 30457.2],
  [43.6166163, -116.200886, 35972.71],
  [49.2608724, -123.113952, 38708.33],
  [45.7566557, 9.7542192, 9034.45],
  [44.0505054, -123.0950506, 879.1500000000001],
  [37.3886303, -5.9953403, 39628.99],
  [62.783333, 15.666667, 47872.75],
  [-34.6083696, -58.4440583, 32438.08],
  [47.2186371, -1.5541362, 52568.31],
  [45.5202471, -122.674194, 51552.22],
  [-23.5506507, -46.6333824, 33471.4],
  [45.5031824, -73.5698065, 49642.96],
  [-34.6083696, -58.4440583, 37777.79],
  [48.8035403, 2.1266886, 54112.67],
  [46.2017559, 6.1466014, 19705.15],
  [51.4893335, -0.1440551, 22104.8],
  [51.4893335, -0.1440551, 338.0],
  [49.4892913, 8.4673098, 52600.34],
  [38.7077507, -9.1365919, 42182.15],
  [48.8588897, 2.320041, 37751.82],
  [-34.6083696, -58.4440583, 26589.09],
  [48.1371079, 11.5753822, 22340.52],
  [-23.5506507, -46.6333824, 38307.47],
  [56.1496278, 10.2134046, 38624.75],
  [47.2186371, -1.5541362, 51023.6],
  [40.4167047, -3.7035825, 46107.46],
  [40.4167047, -3.7035825, 49920.91],
  [17.3156929, -62.7446806, 17326.5],
  [40.4167047, -3.7035825, 32478.8],
  [-22.9110137, -43.2093727, 10965.2],
  [-22.4683626, -44.4463494, 945.45],
  [-22.9056391, -47.059564, 4477.5],
  [45.7566557, 9.7542192, 51559.68],
  [48.584614, 7.7507127, 20744.329999999998],
  [38.7077507, -9.1365919, 37680.49],
  [48.7784485, 9.1800132, 23497.2],
  [35.0841034, -106.650985, 12928.92],
  [50.1106444, 8.6820917, 41135.5],
  [56.1496278, 10.2134046, 2943.4],
  [-22.9110137, -43.2093727, 42458.58],
  [48.8588897, 2.320041, 21693.46],
  [65.0117869, 25.4701983, 46157.8],
  [51.4893335, -0.1440551, 5570.05],
  [-22.9056391, -47.059564, 56323.6],
  [34.0, -40.0, 17521.22],
  [61.2163129, -149.894852, 2414.3900000000003],
  [40.4167047, -3.7035825, 98.0],
  [47.7981346, 13.0464806, 26986.89],
  [47.6765382, -122.2070775, 15058.61],
  [55.6867243, 12.5700724, 45979.4],
  [48.7784485, 9.1800132, 61483.06],
  [-34.6083696, -58.4440583, 10361.9],
  [60.1674881, 24.9427473, 8720.35],
  [50.938361, 6.959974, 15294.869999999999],
  [48.7784485, 9.1800132, 51680.86],
  [-22.9110137, -43.2093727, 25313.4],
  [-34.6083696, -58.4440583, 44718.57],
  [49.4892913, 8.4673098, 13130.95],
  [46.2017559, 6.1466014, 39571.38],
  [42.03726, -88.2810994, 20672.14],
  [46.9484742, 7.4521749, 12349.73],
  [50.938361, 6.959974, 28560.7],
  [51.098481, 14.514475, 50248.97],
  [51.4893335, -0.1440551, 57442.91],
  [45.0677551, 7.6824892, 22122.21],
  [-22.9110137, -43.2093727, 3960.5],
  [50.8465573, 4.351697, 50798.11],
  [49.4892913, 8.4673098, 21742.1],
  [-34.6083696, -58.4440583, 1313.5],
  [61.2163129, -149.894852, 4638.0],
  [50.7633176, -1.2985186, 18599.21],
  [50.776351, 6.083862, 10336.9]],
 [[-22.9110137, -43.2093727, 48463.57],
  [51.3406321, 12.3747329, 11387.0],
  [10.0774374, -69.3222293, 572.0],
  [51.3406321, 12.3747329, 53247.98],
  [46.2017559, 6.1466014, 35477.7],
  [44.0505054, -123.0950506, 382.6],

In [413]:
hmt = folium.Map(location=[0.000, 0.000],
               tiles='cartodbpositron',#'cartodbpositron', stamentoner
               zoom_start=3,
               control_scale=True)

HeatMapWithTime(data1,
                index=time_index1,
                auto_play=True,
                use_local_extrema=True
               ).add_to(hmt)

hmt

Nota los envios del atlantico son porque tienen ciudad None, no porque los atlantes compren algo
Esto es por mes y año,

In [415]:
conn.close()

### **2. Análisis de Desempeño de Productos**
Analiza el desempeño de los productos de la empresa. Examina las ventas de productos por categoría, identificando los productos más vendidos y los menos vendidos. 

Pista: Utiliza gráficos de barras y de tarta para visualizar la participación de mercado de cada categoría y los ingresos generados por los productos individuales.

In [416]:
conn = sqlite3.connect("data/northwind.db")
c = conn.cursor();

In [417]:
from sqlalchemy import create_engine

engine = create_engine("sqlite:///data/northwind.db", echo=False)
connection = engine.connect() #para sacar en dataframe
query="""
SELECT sum((p.UnitPrice*QUANTITY)-DISCOUNT) AS dinero_generado, Categoryname, sum(QUANTITY) as ventas
FROM Products as p
INNER JOIN "Order Details" as od ON od.productid=p.productid
INNER JOIN "Categories" as c ON c.Categoryid=p.Categoryid
group by Categoryname
order by dinero_generado desc




"""
df2=pd.read_sql(query, connection)
df2

   dinero_generado    CategoryName   ventas
0      92204873.25       Beverages  2427361
1      66360755.36     Confections  2628466
2      64908797.15    Meat/Poultry  1207892
3      58052718.24  Dairy Products  2020160
4      55811411.33      Condiments  2420864
5      49939382.08         Seafood  2410782
6      32712524.12         Produce  1010224
7      28579624.87  Grains/Cereals  1412853

In [418]:
fig = {
  "data": [
    {
      "values": df2["dinero_generado"],
      "labels": df2["CategoryName"],
      "domain": {"x": [0, .5]},
      "name": "Number Of Students Rates",
      "hoverinfo":"label+percent+name",
      "hole": 0.3,
      "type": "pie"
    },],
  "layout": {
        "title":"Porcentaje de dinero generado total por categoria de producto",
        "annotations": [
            { "font": { "size": 20},
              "showarrow": False,
              "text": "",
                "x": 0.13,
                "y": 1.1
            },
        ]
    }
}
iplot(fig)

Lo que genera mas dinero son las bebidas seguido de confecciones y carne.
Lo que menos dinero genera es el grano

In [419]:
fig = {
  "data": [
    {
      "values": df2["ventas"],
      "labels": df2["CategoryName"],
      "domain": {"x": [0, .5]},
      "name": "Number Of Students Rates",
      "hoverinfo":"label+percent+name",
      "hole": 0.3,
      "type": "pie"
    },],
  "layout": {
        "title":"Porcentaje de ventas total por categoria de producto",
        "annotations": [
            { "font": { "size": 20},
              "showarrow": False,
              "text": "",
                "x": 0.13,
                "y": 1.1
            },
        ]
    }
}
iplot(fig)

El orden de ventas es igual

In [420]:
query="""
SELECT SUM(QUANTITY) AS unidades_vendidas, Categoryname, productName, sum(((p.UnitPrice*QUANTITY)-DISCOUNT)) AS dinero_generado
FROM Products as p
INNER JOIN "Order Details" as od ON od.productid=p.productid
INNER JOIN "Categories" as c ON c.Categoryid=p.Categoryid
group by ProductName
ORDER BY unidades_vendidas desc




"""
df2_5=pd.read_sql(query, connection)
df2_5

,unidades_vendidas,CategoryName,ProductName,dinero_generado
0,206213,Condiments,Louisiana Hot Spiced Okra,3505620.75
1,205637,Confections,Sir Rodney's Marmalade,16656596.26
2,205487,Confections,Teatime Chocolate Biscuits,1890478.35
3,205005,Condiments,Sirop d'érable,5842640.80
4,204761,Confections,Gumbär Gummibärchen,6394684.38
...,...,...,...,...
72,199042,Seafood,Röd Kaviar,2985629.34
73,199010,Meat/Poultry,Thüringer Rostbratwurst,24635445.85
74,198726,Condiments,Chef Anton's Cajun Seasoning,4371970.50
75,197889,Confections,Zaanse koeken,1879943.95
76,197673,Seafood,Escargots de Bourgogne,2619165.45

In [421]:
df2_5["CategoryName"].unique()

array(['Condiments', 'Confections', 'Beverages', 'Grains/Cereals',
       'Dairy Products', 'Produce', 'Meat/Poultry', 'Seafood'],
      dtype=object)

In [422]:
filtro1=df2_5["CategoryName"]=="Condiments"
df2_1= df2_5[filtro1]

filtro2=df2_5["CategoryName"]=="Confections"
df2_2= df2_5[filtro2]

filtro3=df2_5["CategoryName"]=="Beverages"
df2_3= df2_5[filtro3]

filtro4=df2_5["CategoryName"]=="Grains/Cereals"
df2_4= df2_5[filtro4]

filtro5=df2_5["CategoryName"]=="Dairy Products"
df2_55= df2_5[filtro5]

filtro6=df2_5["CategoryName"]=="Produce"
df2_6= df2_5[filtro6]

filtro7=df2_5["CategoryName"]=="Meat/Poultry"
df2_7= df2_5[filtro7]

filtro8=df2_5["CategoryName"]=="Seafood"
df2_8= df2_5[filtro8]


trace1 = go.Bar(x = df2_1['ProductName'],
               y = df2_1['unidades_vendidas'],
               name =df2_1["CategoryName"].iloc[0],  
               marker = dict(color = 'rgba(255, 174, 255, 0.5)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df2_1['ProductName'])

trace2 = go.Bar(x = df2_2['ProductName'],
               y = df2_2['unidades_vendidas'],
               name =df2_2["CategoryName"].iloc[0],  
               marker = dict(color = 'rgba(58, 255, 136)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df2_2['ProductName'])

trace3 = go.Bar(x = df2_3['ProductName'],
               y = df2_3['unidades_vendidas'],
               name =df2_3["CategoryName"].iloc[0],  
               marker = dict(color = 'rgba(229, 247, 6)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df2_3['ProductName'])

trace4 = go.Bar(x = df2_4['ProductName'],
               y = df2_4['unidades_vendidas'],
               name =df2_4["CategoryName"].iloc[0],  
               marker = dict(color = 'rgba(247, 163, 6)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df2_4['ProductName'])

trace5 = go.Bar(x = df2_55['ProductName'],
               y = df2_55['unidades_vendidas'],
               name =df2_55["CategoryName"].iloc[0],  
               marker = dict(color = 'rgba(6, 247, 207 )',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df2_55['ProductName'])

trace6 = go.Bar(x = df2_6['ProductName'],
               y = df2_6['unidades_vendidas'],
               name =df2_6["CategoryName"].iloc[0],  
               marker = dict(color = 'rgba(6, 141, 247)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df2_6['ProductName'])

trace7 = go.Bar(x = df2_7['ProductName'],
               y = df2_7['unidades_vendidas'],
               name =df2_7["CategoryName"].iloc[0],  
               marker = dict(color = 'rgba(174, 6, 247 )',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df2_7['ProductName'])

trace8 = go.Bar(x = df2_8['ProductName'],
               y = df2_8['unidades_vendidas'],
               name =df2_8["CategoryName"].iloc[0],  
               marker = dict(color = 'rgba(247, 6, 6)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df2_8['ProductName'])




data = [trace1,trace2,trace3,trace4, trace5,trace6,trace7,trace8 ]

layout = go.Layout(barmode = "group")#(puedes meter overlay) #laben

fig = go.Figure(data = data, layout = layout)

iplot(fig)

### ^^Productos mas vendidos POR categoria

Parece que todos los productos se venden igual mas o menos (todos rondan las 200k unidades)

In [423]:
filtro1=df2_5["CategoryName"]=="Condiments"
df2_1= df2_5[filtro1]

filtro2=df2_5["CategoryName"]=="Confections"
df2_2= df2_5[filtro2]

filtro3=df2_5["CategoryName"]=="Beverages"
df2_3= df2_5[filtro3]

filtro4=df2_5["CategoryName"]=="Grains/Cereals"
df2_4= df2_5[filtro4]

filtro5=df2_5["CategoryName"]=="Dairy Products"
df2_55= df2_5[filtro5]

filtro6=df2_5["CategoryName"]=="Produce"
df2_6= df2_5[filtro6]

filtro7=df2_5["CategoryName"]=="Meat/Poultry"
df2_7= df2_5[filtro7]

filtro8=df2_5["CategoryName"]=="Seafood"
df2_8= df2_5[filtro8]


trace1 = go.Bar(x = df2_1['ProductName'],
               y = df2_1['dinero_generado'],
               name =df2_1["CategoryName"].iloc[0],  
               marker = dict(color = 'rgba(255, 174, 255, 0.5)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df2_1['ProductName'])

trace2 = go.Bar(x = df2_2['ProductName'],
               y = df2_2['dinero_generado'],
               name =df2_2["CategoryName"].iloc[0],  
               marker = dict(color = 'rgba(58, 255, 136)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df2_2['ProductName'])

trace3 = go.Bar(x = df2_3['ProductName'],
               y = df2_3['dinero_generado'],
               name =df2_3["CategoryName"].iloc[0],  
               marker = dict(color = 'rgba(229, 247, 6)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df2_3['ProductName'])

trace4 = go.Bar(x = df2_4['ProductName'],
               y = df2_4['dinero_generado'],
               name =df2_4["CategoryName"].iloc[0],  
               marker = dict(color = 'rgba(247, 163, 6)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df2_4['ProductName'])

trace5 = go.Bar(x = df2_55['ProductName'],
               y = df2_55['dinero_generado'],
               name =df2_55["CategoryName"].iloc[0],  
               marker = dict(color = 'rgba(6, 247, 207 )',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df2_55['ProductName'])

trace6 = go.Bar(x = df2_6['ProductName'],
               y = df2_6['dinero_generado'],
               name =df2_6["CategoryName"].iloc[0],  
               marker = dict(color = 'rgba(6, 141, 247)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df2_6['ProductName'])

trace7 = go.Bar(x = df2_7['ProductName'],
               y = df2_7['dinero_generado'],
               name =df2_7["CategoryName"].iloc[0],  
               marker = dict(color = 'rgba(174, 6, 247 )',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df2_7['ProductName'])

trace8 = go.Bar(x = df2_8['ProductName'],
               y = df2_8['dinero_generado'],
               name =df2_8["CategoryName"].iloc[0],  
               marker = dict(color = 'rgba(247, 6, 6)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df2_8['ProductName'])



data = [trace1,trace2,trace3,trace4, trace5,trace6,trace7,trace8 ]

layout = go.Layout(barmode = "group")#(puedes meter overlay) #laben

fig = go.Figure(data = data, layout = layout)

iplot(fig)

* **Condimentos:** lo que mas dinero genera es el veggi spread, Northwoods Cranberry Sauce. Lo que menos se  vende Original Frankfurter grune Sobe. el resto rondas los 4 M de $.
* **Confections:**  Sir Rodney's Marmalade (15 M) es lo que se venden mas,  segido de Tarte au sucre(10M), Schoggi Schokolade y Gumbär Gummibärchen (6,3M). El resto ronda 2 M. 
* **Beverages:** Lo que Cote de Blaye con (50 M) el resto no 10M.
* **Grains/Cereals:** Lo que mas dinero genera es Gnocchi din nnona y el Wimmers gute
* **Dairy Products:** Geitost es lo que menos dinero genera, mientras lo que mas nera es Raclette Courdavault
* **Produce:**  Lo que mas dinero genera es Manjimuo Dried Appels  y Sauerkraut, el tofu en general el lo que menos genera.
* **Meat/Poultry:** Thüringer Rostbratwurst (25 M)  es lo que mas genera Mishi Kobe Niku lo segundo
* **Seafood:** Lo que mas genera es Carnavo Tiger(12,6 M) y ikura, el resto no llega a los 5 M.

In [424]:
conn.close()

### **3. Análisis de Rentabilidad de Clientes**
Analiza la rentabilidad de los clientes de la empresa. Examina los ingresos generados por cada cliente, así como los costos asociados con el servicio o producto proporcionado. 

Pista: Utiliza gráficos de dispersión y tablas dinámicas para identificar los clientes más rentables y aquellos que requieren mayor atención.

In [425]:
engine = create_engine("sqlite:///data/northwind.db", echo=False)
connection = engine.connect() #para sacar en dataframe

In [426]:

query="""
Select c.customerid, sum(od.UnitPrice*od.Quantity-discount) as dinero_generado, CompanyName, productname, count(productname) as veces_que_que_lo_han_comprado
FROM Customers as c
INNER JOIN Orders as o on c.customerid=o.customerid
INNER JOIN "order details" as od on od.orderid=o.orderid
INNER JOIN products as p on p.productid=od.productid
Group by o.orderid
order by dinero_generado desc

"""
df3=pd.read_sql(query, connection)
df3

,CustomerID,dinero_generado,CompanyName,ProductName,veces_que_que_lo_han_comprado
0,RANCH,73431.42,Rancho grande,Spegesild,75
1,WELLI,69796.71,Wellington Importadora,Rhönbräu Klosterbier,74
2,MEREP,69502.71,Mère Paillarde,Sir Rodney's Marmalade,74
3,LONEP,69353.99,Lonesome Pine Restaurant,Perth Pasties,76
4,PRINI,69289.37,Princesa Isabel Vinhos,Côte de Blaye,76
...,...,...,...,...,...
16277,REGGC,27.85,Reggiani Caseifici,Filo Mix,1
16278,FRANS,18.40,Franchi S.p.A.,Boston Crab Meat,1
16279,WOLZA,18.00,Wolski Zajazd,Steeleye Stout,1
16280,BLAUS,18.00,Blauer See Delikatessen,Steeleye Stout,1
16281,CACTU,12.50,Cactus Comidas para llevar,Gorgonzola Telino,1

In [427]:
df3

x = df3.CompanyName

trace1 = {
    'x': df3['CompanyName'],
    'y': df3['dinero_generado'],
    'name': 'CompanyName',
    'type': 'bar'
}

layout = {
    'xaxis': {"title":"Compañia"},
    'yaxis': {"title":"dinero_generado"},
    'barmode': 'group',
    'title': 'Clientes que mas compras'
}
fig = go.Figure(data = trace1, layout = layout)
iplot(fig)

IT es el que el cliente que compra mas. El resto ronda 5 M.

Para cambiar de empresa ejecutar de nuevo celda Resetea lo de arriba

In [428]:
# Algo para sacar las cocsas de los clientes
s=df3["CompanyName"].unique()
list(s).index('Rancho grande')

0

In [429]:
x=-1

In [430]:
range(len(df3["CompanyName"].unique()))

x+=1

if x>=92:
    x=0
df3["CompanyName"][x]
filtro=df3["CompanyName"]==df3["CompanyName"][x]
df3_1=df3[filtro]
name=df3_1["CompanyName"].iloc[0]
fig = {
  "data": [
    {
      "values": df3_1["dinero_generado"],
      "labels": df3_1["ProductName"],
      "domain": {"x": [0, .5]},
      "name": name,
      "hoverinfo":"label+percent+name",
      "hole": 0.3,
      "type": "pie"
    },],
  "layout": {
        "title":f"Lo que compra {name}, {x}",
        "annotations": [
            { "font": { "size": 20},
              "showarrow": False,
              "text": "",
                "x": 0.13,
                "y": 1.1
            },
        ]
    }
}
iplot(fig)

Parece que compra distintas cosas. Un producto nunca genera mas del 5% de los ingresos.

In [431]:

query="""
Select c.customerid, sum(od.UnitPrice*od.Quantity-discount) as dinero_generado, CompanyName, productname, count(productname) as productos_que_compran
FROM Customers as c
INNER JOIN Orders as o on c.customerid=o.customerid
INNER JOIN "order details" as od on od.orderid=o.orderid
INNER JOIN products as p on p.productid=od.productid
Group by CompanyName
order by productos_que_compran desc

"""
df3_2=pd.read_sql(query, connection)
df3_2

,CustomerID,dinero_generado,CompanyName,ProductName,productos_que_compran
0,Val2,9745371.29,IT,Tunnbröd,13283
1,BSBEV,6154115.34,B's Beverages,Aniseed Syrup,8287
2,HUNGC,5698023.67,Hungry Coyote Import Store,Tofu,7808
3,RICAR,5524989.61,Ricardo Adocicados,Pavlova,7595
4,GOURL,5552596.60,Gourmet Lanchonetes,Gorgonzola Telino,7566
...,...,...,...,...,...
87,REGGC,4223747.23,Reggiani Caseifici,Tourtière,5736
88,LEHMS,4186161.31,Lehmanns Marktstand,Alice Mutton,5596
89,FURIB,4099369.97,Furia Bacalhau e Frutos do Mar,Raclette Courdavault,5574
90,OCEAN,4059079.05,Océano Atlántico Ltda.,Tofu,5468
91,ALFKI,3965787.10,Alfreds Futterkiste,Rössle Sauerkraut,5325

In [432]:

x = df3_2.CompanyName

trace1 = {
    'x': x,
    'y': df3_2['productos_que_compran'],
    'name': 'citation',
    'type': 'bar'
}

layout = {
    'xaxis': {"title":"Compañia"},
    'yaxis': {"title":"Cosas que compran"},
    'barmode': 'group',
    'title': 'Clientes que mas compran mas cosas'
}
fig = go.Figure(data = trace1, layout = layout)
iplot(fig)

In [433]:
2

x = df3_2.CompanyName

trace1 = {
    'x': x,
    'y': df3_2['dinero_generado'],
    'name': 'citation',
    'type': 'bar'
}

layout = {
    'xaxis': {"title":"Compañia"},
    'yaxis': {"title":"Cosas dinero_generado"},
    'barmode': 'group',
    'title': 'Clientes que generan mas dinero'
}
fig = go.Figure(data = trace1, layout = layout)
iplot(fig)

Parece que no ha demasiada diferencia entre productos que compran y el dinero que generan.

In [434]:
conn.close()

### **4. Análisis de Inventarios y Proveedores**
Analiza los niveles de inventario y la gestión de proveedores de la empresa. Examina el inventario disponible por categoría de productos, así como el rendimiento de los proveedores en términos de puntualidad de entrega y calidad de los productos. 

Pista: Utiliza gráficos de líneas y tablas dinámicas para mostrar tendencias y comparar el desempeño de los proveedores.

In [435]:
engine = create_engine("sqlite:///data/northwind.db", echo=False)
connection = engine.connect() #para sacar en dataframe

In [436]:
query="""
Select ProductName, UnitsInStock, UnitsOnOrder, ReorderLevel, CompanyName , categoryname                   
FROM Suppliers as s
INNER JOIN products as p ON p.supplierid=s.supplierid
INNER JOIN "Categories" as c ON c.Categoryid=p.Categoryid
Group by ProductName
order by UnitsInStock
"""
df4=pd.read_sql(query, connection)
df4

,ProductName,UnitsInStock,UnitsOnOrder,ReorderLevel,CompanyName,CategoryName
0,Alice Mutton,0,0,0,"Pavlova, Ltd.",Meat/Poultry
1,Chef Anton's Gumbo Mix,0,0,0,New Orleans Cajun Delights,Condiments
2,Gorgonzola Telino,0,70,20,Formaggi Fortini s.r.l.,Dairy Products
3,Perth Pasties,0,0,0,"G'day, Mate",Meat/Poultry
4,Thüringer Rostbratwurst,0,0,0,Plutzer Lebensmittelgroßmärkte AG,Meat/Poultry
...,...,...,...,...,...,...
72,Sirop d'érable,113,0,25,Forêts d'érables,Condiments
73,Pâté chinois,115,0,20,Ma Maison,Meat/Poultry
74,Grandma's Boysenberry Spread,120,0,25,Grandma Kelly's Homestead,Condiments
75,Boston Crab Meat,123,0,30,New England Seafood Cannery,Seafood
76,Rhönbräu Klosterbier,125,0,25,Plutzer Lebensmittelgroßmärkte AG,Beverages

In [437]:
conn.close()

In [438]:
trace1 = {
    'x': df4['ProductName'],
    'y': df4['UnitsInStock'],
    'name': 'En stock',
    'type': 'bar'
}
trace2 = {
    'x': df4['ProductName'],
    'y': df4['UnitsOnOrder'],
    'name': 'Unidades pedidas',
    'type': 'bar'
}

trace3 = {
    'x': df4['ProductName'],
    'y': df4['UnitsOnOrder'],
    'name': 'Nivel de reabastecimiento',
    'type': 'bar'
}
layout = {
    'xaxis': {"title":"Producto"},
    'yaxis': {"title":"Unidades"},
    'barmode': 'group',
    'title': 'Inventario en producto'
}
data=[trace1,trace2,trace3]
fig = go.Figure(data = data, layout = layout)
iplot(fig)

In [439]:
trace1 = {
    'x': df4['CategoryName'],
    'y': df4['UnitsInStock'],
    'name': 'En stock',
    'type': 'bar'
}
trace2 = {
    'x': df4['CategoryName'],
    'y': df4['UnitsOnOrder'],
    'name': 'Unidades pedidas',
    'type': 'bar'
}

trace3 = {
    'x': df4['CategoryName'],
    'y': df4['UnitsOnOrder'],
    'name': 'Nivel de reabastecimiento',
    'type': 'bar'
}
layout = {
    'xaxis': {"title":"Producto"},
    'yaxis': {"title":"Unidades"},
    'barmode': 'group',
    'title': 'Inventario en categoria'
}
data=[trace1,trace2,trace3]
fig = go.Figure(data = data, layout = layout)
iplot(fig)

Curiosamente no se pide carne

In [440]:

query="""
Select ProductName, UnitsInStock, UnitsOnOrder, ReorderLevel, CompanyName , count(ProductName)  as productos_provistos                 
FROM Suppliers as s
INNER JOIN products as p ON p.supplierid=s.supplierid
INNER JOIN "Categories" as c ON c.Categoryid=p.Categoryid
Group by CompanyName
order by UnitsInStock
"""
df4_5=pd.read_sql(query, connection)
df4_5

,ProductName,UnitsInStock,UnitsOnOrder,ReorderLevel,CompanyName,productos_provistos
0,Gorgonzola Telino,0,70,20,Formaggi Fortini s.r.l.,3
1,Rogede sild,5,70,15,Lyngbysild,2
2,Maxilaku,10,60,15,Karkki Oy,3
3,Nord-Ost Matjeshering,10,0,15,Nord-Ost-Fisch Handelsgesellschaft mbH,1
4,Côte de Blaye,17,0,15,Aux joyeux ecclésiastiques,2
5,Manjimup Dried Apples,20,0,10,"G'day, Mate",3
6,Guaraná Fantástica,20,0,0,Refrescos Americanas LTDA,1
7,Tourtière,21,0,10,Ma Maison,2
8,Gnocchi di nonna Alice,21,10,30,Pasta Buttini s.r.l.,2
9,Queso Cabrales,22,30,30,Cooperativa de Quesos 'Las Cabras',2
10,Konbu,24,0,5,Mayumi's,3
11,Teatime Chocolate Biscuits,25,0,5,"Specialty Biscuits, Ltd.",4
12,Singaporean Hokkien Fried Mee,26,0,0,Leka Trading,3
13,Rössle Sauerkraut,26,0,0,Plutzer Lebensmittelgroßmärkte AG,5
14,Pavlova,29,0,10,"Pavlova, Ltd.",5
15,Mishi Kobe Niku,29,0,0,Tokyo Traders,3
16,Zaanse koeken,36,0,0,Zaanse Snoepfabriek,2
17,Chai,39,0,10,Exotic Liquids,3
18,Chef Anton's Cajun Seasoning,53,0,0,New Orleans Cajun Delights,4
19,Escargots de Bourgogne,62,0,20,Escargots Nouveaux,1
20,NuNuCa Nuß-Nougat-Creme,76,0,30,Heli Süßwaren GmbH & Co. KG,3
21,Raclette Courdavault,79,0,0,Gai pâturage,2
22,Gustaf's Knäckebröd,104,0,25,PB Knäckebröd AB,2
23,Sasquatch Ale,111,0,15,Bigfoot Breweries,3
24,Geitost,112,0,20,Norske Meierier,3
25,Inlagd Sill,112,0,20,Svensk Sjöföda AB,3
26,Sirop d'érable,113,0,25,Forêts d'érables,2
27,Grandma's Boysenberry Spread,120,0,25,Grandma Kelly's Homestead,3
28,Boston Crab Meat,123,0,30,New England Seafood Cannery,2

In [441]:
trace1 = {
    'x':df4_5["CompanyName"],
    'y': df4_5['productos_provistos'],
    'name': 'proucto',
    'type': 'bar'}


layout = {
    'xaxis': {"title":"Supplier"},
    'yaxis': {"title":"productos_provistos"},
    'barmode': 'group',
    'title': 'Dependencia de Proveedores'
}
data=[trace1]
fig = go.Figure(data = data, layout = layout)
iplot(fig)

In [442]:
conn.close()

Los provedores que mas mas productos proveen Pavlov y Plutzer Lebensmittelgrobmärkte AG.


### **5. Análisis de Comportamiento de Empleados**
Analiza el comportamiento de los empleados de la empresa. Examina las ventas realizadas por cada empleado, así como su eficiencia en el manejo de pedidos y su puntualidad en la entrega de productos. 

Pista: Utiliza gráficos de barra y de dispersión para comparar el desempeño de los empleados y identificar áreas de mejora.

In [443]:
engine = create_engine("sqlite:///data/northwind.db", echo=False)
connection = engine.connect() #para sacar en dataframe

Todos los empleados venden mas o menos lo mismo. En cuant a ventas y a dinero generado.

In [444]:
query="""
SELECT o.employeeid,FirstName, LastName, count(O.orderid) as ventas , sum(unitprice*quantity-discount) as dinero_generado
from employees as e
inner join orders as o on e.employeeid=o.employeeid
inner join "Order Details" as od on o.OrderID=od.OrderID
group by o.employeeid
order by ventas desc
"""
df5=pd.read_sql(query, connection)
df5

   EmployeeID FirstName   LastName  ventas  dinero_generado
0           4  Margaret    Peacock   69871      51505666.05
1           5    Steven   Buchanan   69868      51393226.77
2           3     Janet  Leverling   68246      50455796.27
3           1     Nancy    Davolio   67619      49669442.35
4           8     Laura   Callahan   67401      49287560.96
5           7    Robert       King   67361      49668614.11
6           2    Andrew     Fuller   66365      48325301.72
7           9      Anne  Dodsworth   66362      49025327.07
8           6   Michael     Suyama   66190      49144242.38

In [445]:
trace1 = go.Bar(x = df5["EmployeeID"],
               y = df5['ventas'],
               name = 'Ventas de cada empleado',
               marker = dict(color = 'rgba(255, 174, 255, 0.5)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df5['LastName'])


data = trace1

layout = go.Layout(barmode = "group")#(puedes meter overlay) #laben

fig = go.Figure(data = data, layout = layout)

iplot(fig)

In [446]:
trace1 = go.Bar(x = df5["EmployeeID"],
               y = df5['dinero_generado'],
               name = 'Ventas de cada empleado',
               marker = dict(color = 'rgba(255, 174, 255, 0.5)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df5['LastName'])


data = trace1

layout = go.Layout(barmode = "group")#(puedes meter overlay) #laben

fig = go.Figure(data = data, layout = layout)

iplot(fig)

Todos los empleados venden mas o menos lo mismo. En cuant a ventas y a dinero generado.

In [447]:
query="""
SELECT o.employeeid,FirstName, LastName, requireddate, shippeddate,orderdate
from employees as e
inner join orders as o on e.employeeid=o.employeeid
inner join "Order Details" as od on o.OrderID=od.OrderID
group by od.OrderID
"""
df5=pd.read_sql(query, connection)
df5

,EmployeeID,FirstName,LastName,RequiredDate,ShippedDate,OrderDate
0,5,Steven,Buchanan,2016-08-01,2016-07-16,2016-07-04
1,6,Michael,Suyama,2016-08-16,2016-07-10,2016-07-05
2,4,Margaret,Peacock,2016-08-05,2016-07-12,2016-07-08
3,3,Janet,Leverling,2016-08-05,2016-07-15,2016-07-08
4,4,Margaret,Peacock,2016-08-06,2016-07-11,2016-07-09
...,...,...,...,...,...,...
16277,6,Michael,Suyama,2013-01-07 03:47:01,2012-12-28 19:03:24,2012-12-26 04:58:22
16278,9,Anne,Dodsworth,2022-09-01 05:09:08,2022-08-10 08:11:43,2022-08-05 06:33:39
16279,4,Margaret,Peacock,2022-02-19 13:46:17,2022-02-23 07:40:46,2022-02-09 08:20:12
16280,9,Anne,Dodsworth,2020-05-22 20:22:49,2020-04-28 11:21:50,2020-04-27 23:05:30
16281,6,Michael,Suyama,2023-02-21 23:37:27,2023-01-10 09:47:23,2023-01-10 05:40:51

In [448]:
df5['RequiredDate'] = pd.to_datetime(df5['RequiredDate'], format="mixed")
df5['ShippedDate'] = pd.to_datetime(df5['ShippedDate'], format="mixed")
df5['OrderDate'] = pd.to_datetime(df5['OrderDate'], format="mixed")
df5

,EmployeeID,FirstName,LastName,RequiredDate,ShippedDate,OrderDate
0,5,Steven,Buchanan,2016-08-01 00:00:00,2016-07-16 00:00:00,2016-07-04 00:00:00
1,6,Michael,Suyama,2016-08-16 00:00:00,2016-07-10 00:00:00,2016-07-05 00:00:00
2,4,Margaret,Peacock,2016-08-05 00:00:00,2016-07-12 00:00:00,2016-07-08 00:00:00
3,3,Janet,Leverling,2016-08-05 00:00:00,2016-07-15 00:00:00,2016-07-08 00:00:00
4,4,Margaret,Peacock,2016-08-06 00:00:00,2016-07-11 00:00:00,2016-07-09 00:00:00
...,...,...,...,...,...,...
16277,6,Michael,Suyama,2013-01-07 03:47:01,2012-12-28 19:03:24,2012-12-26 04:58:22
16278,9,Anne,Dodsworth,2022-09-01 05:09:08,2022-08-10 08:11:43,2022-08-05 06:33:39
16279,4,Margaret,Peacock,2022-02-19 13:46:17,2022-02-23 07:40:46,2022-02-09 08:20:12
16280,9,Anne,Dodsworth,2020-05-22 20:22:49,2020-04-28 11:21:50,2020-04-27 23:05:30
16281,6,Michael,Suyama,2023-02-21 23:37:27,2023-01-10 09:47:23,2023-01-10 05:40:51

In [449]:
df5["Margen"]=(df5["ShippedDate"]-df5['RequiredDate'])
df5

,EmployeeID,FirstName,LastName,RequiredDate,ShippedDate,OrderDate,Margen
0,5,Steven,Buchanan,2016-08-01 00:00:00,2016-07-16 00:00:00,2016-07-04 00:00:00,-16 days +00:00:00
1,6,Michael,Suyama,2016-08-16 00:00:00,2016-07-10 00:00:00,2016-07-05 00:00:00,-37 days +00:00:00
2,4,Margaret,Peacock,2016-08-05 00:00:00,2016-07-12 00:00:00,2016-07-08 00:00:00,-24 days +00:00:00
3,3,Janet,Leverling,2016-08-05 00:00:00,2016-07-15 00:00:00,2016-07-08 00:00:00,-21 days +00:00:00
4,4,Margaret,Peacock,2016-08-06 00:00:00,2016-07-11 00:00:00,2016-07-09 00:00:00,-26 days +00:00:00
...,...,...,...,...,...,...,...
16277,6,Michael,Suyama,2013-01-07 03:47:01,2012-12-28 19:03:24,2012-12-26 04:58:22,-10 days +15:16:23
16278,9,Anne,Dodsworth,2022-09-01 05:09:08,2022-08-10 08:11:43,2022-08-05 06:33:39,-22 days +03:02:35
16279,4,Margaret,Peacock,2022-02-19 13:46:17,2022-02-23 07:40:46,2022-02-09 08:20:12,3 days 17:54:29
16280,9,Anne,Dodsworth,2020-05-22 20:22:49,2020-04-28 11:21:50,2020-04-27 23:05:30,-25 days +14:59:01
16281,6,Michael,Suyama,2023-02-21 23:37:27,2023-01-10 09:47:23,2023-01-10 05:40:51,-43 days +10:09:56

In [450]:
dias_margen=[(df5["Margen"].iloc[x]).days for x in range(16282)]
dias_margen

[-16,
 -37,
 -24,
 -21,
 -26,
 -8,
 -16,
 -25,
 -26,
 -22,
 -22,
 -21,
 -18,
 -17,
 -25,
 -20,
 2,
 -10,
 -37,
 -20,
 -25,
 -5,
 -27,
 1,
 -24,
 -21,
 -18,
 -26,
 -8,
 -24,
 -24,
 -25,
 1,
 -7,
 -22,
 -21,
 -20,
 -22,
 -19,
 -22,
 -17,
 -26,
 -21,
 -20,
 -23,
 -15,
 -22,
 -20,
 -20,
 -36,
 -22,
 -21,
 -19,
 -20,
 1,
 -21,
 -23,
 -2,
 -21,
 -20,
 -22,
 6,
 -21,
 -8,
 -18,
 -18,
 -19,
 -21,
 -17,
 -18,
 -25,
 -19,
 1,
 -20,
 -9,
 -21,
 -26,
 -9,
 -24,
 -25,
 -25,
 -34,
 -16,
 -37,
 -38,
 -21,
 -21,
 -26,
 -26,
 -23,
 -24,
 -21,
 -18,
 -21,
 -9,
 -22,
 -24,
 -21,
 -39,
 -26,
 -20,
 -21,
 -6,
 -19,
 -8,
 -16,
 -22,
 -23,
 -19,
 -15,
 -21,
 -23,
 -18,
 -17,
 -25,
 -20,
 -34,
 -23,
 -10,
 -24,
 -25,
 -21,
 -4,
 -7,
 -23,
 -22,
 -24,
 -25,
 -24,
 -24,
 -19,
 -26,
 7,
 -27,
 -25,
 -26,
 -24,
 -22,
 -7,
 -26,
 -27,
 -24,
 -25,
 -20,
 -20,
 -19,
 -19,
 -20,
 -4,
 -22,
 -18,
 -6,
 -13,
 -19,
 -34,
 -22,
 -23,
 -12,
 -36,
 -5,
 -22,
 -23,
 -23,
 -17,
 -26,
 -26,
 -25,
 -19,
 -17,
 -16,
 -21,
 -18,
 -22,
 -36,
 -19,
 18,
 -24,
 -7,
 -18,
 7,
 -21,
 -33,
 -10,
 -6,
 -7,
 1,
 -18,
 -39,
 -22,
 -21,
 -20,
 -25,
 -10,
 -10,
 -21,
 -26,
 -19,
 -21,
 -23,
 -7,
 -21,
 -19,
 -8,
 7,
 -22,
 -23,
 -24,
 -35,
 -39,
 -22,
 -22,
 -27,
 -25,
 -23,
 -13,
 -26,
 -18,
 -19,
 -21,
 -23,
 -23,
 -24,
 -25,
 -21,
 -21,
 -6,
 -20,
 -7,
 -21,
 -20,
 -6,
 -26,
 -24,
 -23,
 -8,
 4,
 -20,
 -8,
 -21,
 -26,
 -22,
 -16,
 -25,
 -20,
 -18,
 -20,
 -21,
 -20,
 -25,
 -25,
 -24,
 -20,
 -20,
 -21,
 -9,
 -23,
 -21,
 -21,
 -11,
 -21,
 -1,
 -16,
 -18,
 -25,
 -25,
 -36,
 -4,
 16,
 -21,
 -23,
 -4,
 -25,
 -26,
 -25,
 -22,
 1,
 -22,
 -7,
 -18,
 -26,
 -11,
 -26,
 -24,
 -17,
 -25,
 -18,
 -26,
 -20,
 -5,
 -9,
 -27,
 -21,
 -3,
 -18,
 -22,
 -26,
 -19,
 7,
 -24,
 -18,
 -21,
 -11,
 -19,
 -33,
 -21,
 -24,
 -22,
 -26,
 -32,
 -11,
 -22,
 -20,
 -25,
 -25,
 -25,
 -28,
 -22,
 -21,
 -22,
 -23,
 -2,
 -3,
 -26,
 -25,
 -21,
 -27,
 -17,
 -4,
 -7,
 -35,
 3,
 -19,
 -23,
 -22,
 -11,
 -24,
 -24,
 -19,
 -21,
 -21,
 -21,
 -18,
 -21,
 -5,
 -20,
 7,
 -21,
 -24,
 4,
 -21,
 -24,
 -36,
 -23,
 -36,
 -23,
 -7,
 -17,
 -20,
 -19,
 -25,
 -19,
 -22,
 -16,
 -21,
 -24,
 -25,
 -25,
 -21,
 -23,
 -24,
 -35,
 -25,
 -19,
 -22,
 -23,
 -23,
 -16,
 -22,
 -19,
 -32,
 -20,
 -20,
 -22,
 -27,
 -23,
 -25,
 -22,
 -25,
 -21,
 -21,
 -16,
 -21,
 -21,
 -24,
 -14,
 -20,
 -21,
 -21,
 -35,
 -7,
 -30,
 -27,
 -23,
 -18,
 -21,
 -11,
 -19,
 -20,
 -22,
 -17,
 -25,
 -23,
 9,
 -22,
 -19,
 9,
 -19,
 -22,
 -18,
 -21,
 -20,
 -21,
 -26,
 -21,
 -5,
 -27,
 -16,
 -24,
 -21,
 -24,
 -5,
 -21,
 -26,
 -23,
 -22,
 -23,
 -24,
 -10,
 -20,
 2,
 -8,
 -22,
 -27,
 -23,
 -18,
 -10,
 -25,
 -35,
 -36,
 -22,
 -20,
 -24,
 -22,
 -12,
 -34,
 -22,
 -4,
 6,
 -23,
 -7,
 -23,
 6,
 -25,
 -34,
 -18,
 -26,
 -23,
 -8,
 -25,
 -23,
 -26,
 -19,
 -6,
 -26,
 -36,
 -2,
 -36,
 -23,
 18,
 4,
 -21,
 -32,
 -19,
 -20,
 -27,
 -25,
 -23,
 -17,
 -18,
 -21,
 -22,
 -23,
 -16,
 -10,
 -24,
 -24,
 -21,
 -19,
 -26,
 -21,
 -20,
 1,
 -25,
 -19,
 -24,
 -26,
 -26,
 -26,
 -23,
 -10,
 -22,
 -14,
 -19,
 -22,
 -21,
 -23,
 -23,
 -23,
 -24,
 -18,
 -21,
 -24,
 -20,
 -5,
 -19,
 -23,
 -13,
 -14,
 -25,
 23,
 -20,
 1,
 -5,
 -26,
 -23,
 -27,
 -24,
 -22,
 -24,
 -7,
 0,
 -19,
 -24,
 -19,
 -20,
 -13,
 -19,
 -1,
 -8,
 -17,
 -18,
 -32,
 -18,
 -26,
 -24,
 -21,
 -20,
 -18,
 -23,
 2,
 -20,
 -22,
 -22,
 -22,
 -18,
 -24,
 -19,
 -19,
 1,
 -7,
 -23,
 -19,
 -22,
 -21,
 -20,
 -24,
 -7,
 -23,
 -3,
 11,
 8,
 -18,
 -34,
 -19,
 -23,
 -20,
 -24,
 -22,
 -23,
 -21,
 -24,
 -25,
 -14,
 -19,
 -19,
 -23,
 -23,
 -5,
 -41,
 5,
 -22,
 -21,
 -35,
 -21,
 -10,
 -21,
 -19,
 -20,
 -15,
 -19,
 -23,
 -24,
 -22,
 -10,
 -39,
 -13,
 -21,
 -4,
 -19,
 -34,
 -9,
 -23,
 -19,
 -23,
 -24,
 -25,
 -23,
 -3,
 -25,
 -18,
 -26,
 -26,
 -34,
 -21,
 -19,
 -20,
 -27,
 -22,
 -11,
 -25,
 -21,
 -21,
 -26,
 -26,
 -26,
 -26,
 -26,
 -23,
 -20,
 -22,
 -14,
 -22,
 -16,
 -25,
 -20,
 -20,
 -25,
 -18,
 -8,
 -26,
 -20,
 -16,
 -22,
 -21,
 -8,
 -22,
 -25,
 -25,
 -18,
 -19,
 -19,
 -26,
 -22,
 -36,
 -26,
 -32,
 7,
 -19,
 -21,
 6,
 -15,
 -21,
 -30,
 -1,
 -10,
 -18,
 -25,
 -19,
 -19,
 -11,
 -22,
 -25,
 -16,
 -19,
 -21,
 -20,
 -13,
 -22,
 -21,
 -25,
 -22,
 -24,
 -21,
 -20,
 -34,
 -5,
 -39,
 -25,
 -39,
 -19,
 -19,
 -37,
 6,
 -17,
 -24,
 -21,
 -24,
 -18,
 -9,
 -18,
 -19,
 -21,
 17,
 -19,
 -26,
 -25,
 -5,
 -26,
 -33,
 -13,
 0,
 -23,
 -21,
 -22,
 -16,
 -18,
 -24,
 -25,
 -6,
 -22,
 -18,
 -26,
 -36,
 -22,
 -26,
 -19,
 -7,
 -24,
 -20,
 -32,
 0,
 -21,
 -20,
 -20,
 -18,
 -26,
 -15,
 -25,
 -20,
 -23,
 nan,
 -26,
 -16,
 -24,
 -6,
 -27,
 -23,
 -4,
 -25,
 -21,
 -25,
 nan,
 -26,
 -21,
 -8,
 -4,
 -23,
 -19,
 -15,
 -24,
 -22,
 -17,
 -18,
 -21,
 -22,
 -22,
 -35,
 -24,
 -26,
 -22,
 -19,
 nan,
 nan,
 -22,
 -5,
 -21,
 -20,
 nan,
 -27,
 -21,
 -22,
 -18,
 -20,
 nan,
 -24,
 -26,
 nan,
 -21,
 -11,
 -26,
 nan,
 nan,
 -24,
 nan,
 nan,
 -22,
 -25,
 nan,
 -25,
 -12,
 nan,
 -26,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 -29,
 -5,
 -47,
 -42,
 6,
 -17,
 -34,
 -39,
 -9,
 0,
 -15,
 -4,
 -11,
 3,
 -11,
 -41,
 18,
 8,
 -5,
 -5,
 -9,
 -10,
 -14,
 -9,
 -16,
 -25,
 -42,
 -41,
 16,
 -4,
 -28,
 7,
 -6,
 -41,
 -38,
 -13,
 21,
 -17,
 -17,
 -1,
 -19,
 0,
 -6,
 -18,
 -7,
 17,
 7,
 -3,
 6,
 -27,
 3,
 8,
 -13,
 8,
 -30,
 -15,
 -37,
 -17,
 -19,
 -16,
 -25,
 -23,
 1,
 16,
 2,
 -14,
 -12,
 -32,
 15,
 1,
 -43,
 -9,
 -5,
 -18,
 2,
 -26,
 6,
 -1,
 -16,
 -24,
 6,
 -41,
 -6,
 -8,
 -11,
 -1,
 4,
 -5,
 10,
 -9,
 2,
 -17,
 -4,
 0,
 -6,
 8,
 -12,
 -36,
 15,
 -20,
 -15,
 -3,
 7,
 13,
 18,
 -41,
 -18,
 -38,
 -2,
 -41,
 -29,
 -26,
 13,
 -38,
 -5,
 12,
 -5,
 -22,
 -17,
 -18,
 -32,
 -10,
 19,
 -26,
 -25,
 -6,
 -18,
 3,
 -11,
 2,
 -20,
 17,
 23,
 -40,
 -24,
 -27,
 -15,
 -10,
 4,
 -49,
 -23,
 -7,
 7,
 -30,
 16,
 -5,
 2,
 -23,
 -1,
 -8,
 5,
 -21,
 -20,
 4,
 -15,
 -19,
 -28,
 -1,
 -1,
 -31,
 -11,
 -15,
 0,
 -2,
 -17,
 8,
 5,
 -9,
 -34,
 -22,
 ...]

In [451]:
df5["Margen_dia"]=np.array(dias_margen)
filtro=df5["Margen_dia"]>0
df5_retrasos=df5[filtro]
df5_retrasos

,EmployeeID,FirstName,LastName,RequiredDate,ShippedDate,OrderDate,Margen,Margen_dia
16,6,Michael,Suyama,2016-08-21 00:00:00,2016-08-23 00:00:00,2016-07-24 00:00:00,2 days 00:00:00,2.0
23,6,Michael,Suyama,2016-08-29 00:00:00,2016-08-30 00:00:00,2016-08-01 00:00:00,1 days 00:00:00,1.0
32,2,Andrew,Fuller,2016-09-11 00:00:00,2016-09-12 00:00:00,2016-08-14 00:00:00,1 days 00:00:00,1.0
54,4,Margaret,Peacock,2016-10-08 00:00:00,2016-10-09 00:00:00,2016-09-10 00:00:00,1 days 00:00:00,1.0
61,3,Janet,Leverling,2016-10-17 00:00:00,2016-10-23 00:00:00,2016-09-19 00:00:00,6 days 00:00:00,6.0
...,...,...,...,...,...,...,...,...
16260,7,Robert,King,2016-02-24 05:35:43,2016-03-05 07:28:48,2016-02-19 18:44:01,10 days 01:53:05,10.0
16269,7,Robert,King,2020-07-25 07:54:22,2020-08-02 12:45:10,2020-07-13 13:58:49,8 days 04:50:48,8.0
16271,3,Janet,Leverling,2022-08-29 09:53:29,2022-09-07 05:45:13,2022-08-26 16:17:42,8 days 19:51:44,8.0
16272,4,Margaret,Peacock,2013-07-29 07:19:32,2013-08-11 07:23:03,2013-07-27 20:23:48,13 days 00:03:31,13.0
16279,4,Margaret,Peacock,2022-02-19 13:46:17,2022-02-23 07:40:46,2022-02-09 08:20:12,3 days 17:54:29,3.0

In [452]:
filtro1=df5_retrasos["EmployeeID"]==1
df5_1= df5_retrasos[filtro1]

filtro2=df5_retrasos["EmployeeID"]==2
df5_2= df5_retrasos[filtro2]

filtro3=df5_retrasos["EmployeeID"]==3
df5_3= df5_retrasos[filtro3]

filtro4=df5_retrasos["EmployeeID"]==4
df5_4= df5_retrasos[filtro4]

filtro5=df5_retrasos["EmployeeID"]==5
df5_5= df5_retrasos[filtro5]

filtro6=df5_retrasos["EmployeeID"]==6
df5_6= df5_retrasos[filtro6]

filtro7=df5_retrasos["EmployeeID"]==7
df5_7= df5_retrasos[filtro7]

filtro8=df5_retrasos["EmployeeID"]==8
df5_8= df5_retrasos[filtro8]

filtro9=df5_retrasos["EmployeeID"]==9
df5_9= df5_retrasos[filtro9]

trace1 = go.Box(
               y = df5_1['Margen_dia'],
               name =1,  
               marker = dict(color = 'rgba(255, 174, 255, 0.5)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df5_1['EmployeeID'])

trace2 = go.Box(
               y = df5_2['Margen_dia'],
               name =2,  
               marker = dict(color = 'rgba(58, 255, 136, 0.5)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df5_2['EmployeeID'])

trace3 = go.Box(
               y = df5_3['Margen_dia'],
               name =3,  
               marker = dict(color = 'rgba(229, 247, 6, 0.5)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df5_3['EmployeeID'])

trace4 = go.Box(
               y = df5_4['Margen_dia'],
               name =4,  
               marker = dict(color = 'rgba(247, 163, 6, 0.5)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df5_4['EmployeeID'])

trace5 = go.Box(
               y = df5_5['Margen_dia'],
               name =5,  
               marker = dict(color = 'rgba(6, 247, 207, 0.5 )',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df5_5['EmployeeID'])

trace6 = go.Box(
               y = df5_6['Margen_dia'],
               name =6,  
               marker = dict(color = 'rgba(6, 141, 247, 0.5)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df5_6['EmployeeID'])

trace7 = go.Box(
               y = df5_7['Margen_dia'],
               name =7,  
               marker = dict(color = 'rgba(174, 6, 247, 0.5 )',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df5_7['EmployeeID'])

trace8 = go.Box(
               y = df5_8['Margen_dia'],
               name =8,  
               marker = dict(color = 'rgba(247, 6, 6, 0.5)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df5_8['EmployeeID'])

trace9 = go.Box(
               y = df5_9['Margen_dia'],
               name =9,  
               marker = dict(color = 'rgba(200 47, 6, 6, 0.5)',
                            line = dict(color='rgb(0,0,0)', width = 1.5)),
               text = df5_9['EmployeeID'])



data = [trace1,trace2,trace3,trace4, trace5,trace6,trace7,trace8,trace9]


fig = go.Figure(data = data, layout = layout)

iplot(fig)

In [453]:
print(1,df5_1.shape)
print(2,df5_2.shape)
print(3,df5_3.shape)
print(4,df5_4.shape)
print(5,df5_5.shape)
print(6,df5_6.shape)
print(7,df5_7.shape)
print(8,df5_8.shape)
print(9,df5_9.shape)

1 (366, 8)
2 (332, 8)
3 (386, 8)
4 (386, 8)
5 (360, 8)
6 (362, 8)
7 (395, 8)
8 (373, 8)
9 (384, 8)

Esta grafica tiene todos los retrasos de envio de todos los empleados.
Parece que el empleado mas fiable es es el empleado 2  ya que es el empeado cuya mediana y percentiles son mas bajos. Esto es en cierta manera esperable porque es  es el empleado que menos dinero genera y ventas tiene. De hecho es es el empleado con menos retrasos(332)
El empleado 4, 5 y 7 serian los siguientes mas fiables la una diferencia que tendiras seraian mas outliers su media de dias con retraso es de 6 en vez de 5. La diferencia es que el empleado 4  es el empleado que mas dinero y ventas genera. Es el segundo empleado que mas vende y genera y apenas tiene tanto cuando tiene retraso apenas tiene diferencia con el empleado 4. Sin embargo el empleado 5 cometio menos retrasos que el 4(5: 360, 4:386). Curiosamente el empleado 7 es el empleado con mas retrasos(395).

El peor empleado estaria entre 3 y 6. Ambos tienen los mismos percentiles, pero de entre los dos el empleado 3 tuvo mas retrasos de entre los dos (386 vs 362)  aunque el empleado 6 es el empleado con los retrasos mas graves (27 dias). Sin embargo el empleado 3 genero mas dinero y ventas que el empleado 6 (1 M de diferencia).

El resto esta estaria pr el mismo nivel.

In [454]:
conn.close()